document.write(
        '<title>Konzern eKM</title>'
		+'<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></meta>'
		+'<meta http-equiv="Cache-Control" content="max-age=0" />'
		+'<meta http-equiv="Cache-Control" content="no-cache" />'
		+'<meta http-equiv="expires" content="0" />'
		+'<meta http-equiv="Expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />'
		+'<meta http-equiv="Pragma" content="no-cache" />'
		+'<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10" />'
		+'<link type="text/css" rel="stylesheet" href="styles/_import_styles.css" />'
		+'<link type="text/css" rel="stylesheet" href="styles/zz-htmlMockup-specific.css" />'
		+'<link type="text/css" rel="stylesheet" href="styles/updade_eKm.css?v=3-2-1-7" />'
		+'<link rel="stylesheet" type="text/css" href="styles/xp.css" />'
		+'<script type="text/javascript" src="scripts/validator.js"></script>'
		+'<script type="text/javascript" src="scripts/browser-detect.js"></script>'
		+'<script type="text/javascript" src="scripts/wo_waiting_page.js"></script>'
		+'<script type="text/javascript" src="scripts/print.js"></script>'
		+'<script type="text/javascript" src="scripts/__nowSciptLoader.js"></script>'
);	