update T_ELEMENTVERSIONANDERUNG set ANDERUNG_ART='Neuer Stand' where ANDERUNG_ART like 'Neuer Stand%';

update T_BAUSTEIN set BIBLIOTHEK_REF_ID = 2 where BIBLIOTHEK_REF_ID = 3 ;
update T_BENUTZER set DEFAULT_BIBLIOTHEK_REF_ID = 2 where DEFAULT_BIBLIOTHEK_REF_ID = 3 ; 
delete from T_BIBLIOTHEK where ID = 3;

ALTER TABLE T_REL_ELEMVERSION_NUTZER ADD AKTIV NUMBER(1,0) DEFAULT 0;
commit;