DROP TABLE T_MARKE CASCADE CONSTRAINTS;  
DROP TABLE T_BIBLIOTHEK CASCADE CONSTRAINTS;  
DROP TABLE T_REL_ELEMVERSION_NUTZER CASCADE CONSTRAINTS; 
DROP TABLE T_BAUSTEINSTAND CASCADE CONSTRAINTS; 
DROP TABLE T_REL_BAUSVERSION_NUTZER CASCADE CONSTRAINTS; 

  -- TABLE T_MARKE
 CREATE TABLE T_MARKE 
( ID varchar2(3 char) not null
, NUTZUNG_IMG varchar2(50) not null
, BESITZUNG_IMG varchar2(50) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

 ALTER TABLE T_MARKE ADD (CONSTRAINT T_MARKE_PK PRIMARY KEY (ID) USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);

 -- TABLE T_BIBLIOTHEK
 CREATE TABLE T_BIBLIOTHEK 
( ID NUMBER(12) not null
, NAME varchar2(50) not null
, COLOR varchar2(50) not null
, MARKE_REF_ID varchar2(3 char) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@; 

 ALTER TABLE T_BIBLIOTHEK ADD (CONSTRAINT T_BIBLIOTHEK_PK PRIMARY KEY (ID) USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
 
 ALTER TABLE T_BIBLIOTHEK ADD (CONSTRAINT BIB_MARKE_REF_FK FOREIGN KEY (MARKE_REF_ID) REFERENCES T_MARKE (ID));

 -- TABLE T_REL_ELEMVERSION_NUTZER
 CREATE TABLE T_REL_ELEMVERSION_NUTZER 
( ID NUMBER(12) not null
, KE_VERSION_REF_ID NUMBER(12) not null
, MARKE_REF_ID varchar2(3 char) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@; 

 ALTER TABLE T_REL_ELEMVERSION_NUTZER ADD (CONSTRAINT T_REL_ELEMVERSION_NUTZER_PK PRIMARY KEY (ID) USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
 
 ALTER TABLE T_REL_ELEMVERSION_NUTZER ADD CONSTRAINT ELEM_NUTZER_MARKE_REF_FK FOREIGN KEY (MARKE_REF_ID) REFERENCES T_MARKE (ID); 
 
 ALTER TABLE T_REL_ELEMVERSION_NUTZER ADD CONSTRAINT KE_VERSION_REF_ID_FK FOREIGN KEY (KE_VERSION_REF_ID) REFERENCES T_ELEMENTVERSION (UUIDKEVERSION); 
   
 -- TABLE T_BAUSTEINSTAND
 CREATE TABLE T_BAUSTEINSTAND 
( ID NUMBER(12) not null
, STAND_DATE DATE not null
, STAND_NUMMER NUMBER(9) DEFAULT 1
, KB_VERSION_REF_ID NUMBER(12) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@; 

 ALTER TABLE T_BAUSTEINSTAND ADD (CONSTRAINT T_BAUSTEINSTAND_PK PRIMARY KEY (ID) USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
 
 ALTER TABLE T_BAUSTEINSTAND ADD CONSTRAINT KB_VERSION_REF_FK FOREIGN KEY (KB_VERSION_REF_ID) REFERENCES T_BAUSTEINVERSION (KB_VERSION_UU_ID); 
 
 -- TABLE T_REL_BAUSVERSION_NUTZER
 CREATE TABLE T_REL_BAUSVERSION_NUTZER 
( ID NUMBER(12) not null
, KB_STAND_ID NUMBER(12) not null
, MARKE_REF_ID varchar2(3 char) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@; 

 ALTER TABLE T_REL_BAUSVERSION_NUTZER ADD (CONSTRAINT T_REL_BAUSVERSION_NUTZER_PK PRIMARY KEY (ID) USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
 
 ALTER TABLE T_REL_BAUSVERSION_NUTZER ADD (CONSTRAINT BAUS_NUTZER_MARKE_REF_FK FOREIGN KEY (MARKE_REF_ID) REFERENCES T_MARKE (ID)); 
 
 ALTER TABLE T_REL_BAUSVERSION_NUTZER ADD CONSTRAINT KB_STAND_REF_FK FOREIGN KEY (KB_STAND_ID) REFERENCES T_BAUSTEINSTAND (ID);  
 
 -- TABLE T_ARBEITSBEREICH
 ALTER TABLE T_ARBEITSBEREICH ADD MARKE_REF_ID VARCHAR2(3 char) ;
 ALTER TABLE T_ARBEITSBEREICH ADD (CONSTRAINT ARB_MARKE_REF_FK FOREIGN KEY (MARKE_REF_ID) REFERENCES T_MARKE (ID)); 
 
 -- TABLE T_BENUTZER
 ALTER TABLE T_BENUTZER ADD DEFAULT_MARKE_REF_ID VARCHAR2(3 char) ;
 ALTER TABLE T_BENUTZER ADD DEFAULT_BIBLIOTHEK_REF_ID NUMBER(12) ;
 
 ALTER TABLE T_BENUTZER ADD (CONSTRAINT BEN_MARKE_REF_FK FOREIGN KEY (DEFAULT_MARKE_REF_ID) REFERENCES T_MARKE (ID));  
 
 ALTER TABLE T_BENUTZER ADD (CONSTRAINT BEN_BIBLIOTHEK_REF_FK FOREIGN KEY (DEFAULT_BIBLIOTHEK_REF_ID) REFERENCES T_BIBLIOTHEK (ID));
 
 -- TABLE T_BAUSTEIN
 ALTER TABLE T_BAUSTEIN ADD BESITZER VARCHAR2(3 char) ;
 ALTER TABLE T_BAUSTEIN ADD BIBLIOTHEK_REF_ID NUMBER(12) ;
  
 ALTER TABLE T_BAUSTEIN ADD (CONSTRAINT KB_BESITZER_FK FOREIGN KEY (BESITZER) REFERENCES T_MARKE (ID));   
 ALTER TABLE T_BAUSTEIN ADD (CONSTRAINT KB_BIBLIOTHEK_REF_FK FOREIGN KEY (BIBLIOTHEK_REF_ID) REFERENCES T_BIBLIOTHEK (ID));
 
 -- TABLE T_ELEMENT
 ALTER TABLE T_ELEMENT ADD BESITZER VARCHAR2(3 char) ;
 
 ALTER TABLE T_ELEMENT ADD (CONSTRAINT KE_BESITZER_FK FOREIGN KEY (BESITZER) REFERENCES T_MARKE (ID)); 
 
DROP SEQUENCE SEQ_LIBRARY; 
 PROMPT Creating Sequence 'seq_library';
CREATE SEQUENCE seq_library
 INCREMENT BY 1
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;
 
DROP SEQUENCE SEQ_ELEMVERSION_NUTZER; 
PROMPT Creating Sequence 'SEQ_ELEMVERSION_NUTZER';
CREATE SEQUENCE SEQ_ELEMVERSION_NUTZER
 INCREMENT BY 1
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;
 
PROMPT Creating Sequence 'SEQ_BAUSVERSION_NUTZER';
CREATE SEQUENCE SEQ_BAUSVERSION_NUTZER
 INCREMENT BY 1
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;

PROMPT Creating Sequence 'SEQ_BAUSTEINSTAND';
CREATE SEQUENCE SEQ_BAUSTEINSTAND
 INCREMENT BY 1
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE; 
PROMPT 'INIT DATA';
INSERT INTO T_MARKE( ID, NUTZUNG_IMG,BESITZUNG_IMG) VALUES ('AU','nutzer_AU.jpg','besitzer_AU.jpg');
INSERT INTO T_MARKE( ID, NUTZUNG_IMG,BESITZUNG_IMG) VALUES ('VW','nutzer_VW.jpg','besitzer_VW.jpg'); 
INSERT INTO T_BIBLIOTHEK ( ID,NAME, COLOR, MARKE_REF_ID) VALUES (1,'Komponenten_KAL Audi','read','AU');
INSERT INTO T_BIBLIOTHEK ( ID,NAME, COLOR, MARKE_REF_ID) VALUES (2,'Komponenten_KAL VW','blue','VW');
INSERT INTO T_BIBLIOTHEK ( ID,NAME, COLOR, MARKE_REF_ID) VALUES (3,'ErgänzungsBib VW','gray','VW');
 
select seq_library.NEXTVAL from dual;
select seq_library.NEXTVAL from dual;
select seq_library.NEXTVAL from dual;

 