ALTER TABLE T_ELEMENTVERSION ADD VERSION_NUMMER NUMBER(9,0);
UPDATE T_ELEMENTVERSION X SET VERSION_NUMMER = (select count(UUIDKEVERSION) from T_ELEMENTVERSION where KE_REF_UU_ID=X.KE_REF_UU_ID and UUIDKEVERSION<=X.UUIDKEVERSION and ENUM_STATUS_REF_ID=5) WHERE ENUM_STATUS_REF_ID=5;
ALTER TABLE T_BAUSTEINVERSION ADD VERSION_NUMMER NUMBER(9,0);
UPDATE T_BAUSTEINVERSION X SET VERSION_NUMMER = (select count(KB_VERSION_UU_ID) from T_BAUSTEINVERSION where KB_REF_UU_ID=X.KB_REF_UU_ID and KB_VERSION_UU_ID<=X.KB_VERSION_UU_ID and ENUM_STATUS_REF_ID=5) WHERE ENUM_STATUS_REF_ID=5;

COMMIT;