UPDATE T_BIBLIOTHEK SET COLOR='ak.gif' WHERE MARKE_REF_ID ='AU';
UPDATE T_BIBLIOTHEK SET COLOR='vk.gif' WHERE MARKE_REF_ID ='VW';

UPDATE T_MARKE SET NUTZUNG_IMG='an.jpg', BESITZUNG_IMG= 'ab.jpg' WHERE ID ='AU';
UPDATE T_MARKE SET NUTZUNG_IMG='vn.jpg', BESITZUNG_IMG= 'vb.jpg' WHERE ID ='VW';
COMMIT;