ALTER TABLE T_ORDNER ADD ERSTELLER_REF_ID NUMBER (10,0);
ALTER TABLE T_REL_BAUSVERSION_NUTZER ADD AKTIV NUMBER(1,0) DEFAULT 0;

UPDATE T_REL_BAUSVERSION_NUTZER SET AKTIV = 0 WHERE AKTIV is NULL;
commit;