UPDATE T_ELEMENT SET BESITZER = 'AU';
UPDATE T_BAUSTEIN SET BESITZER = 'AU';
UPDATE T_BAUSTEIN SET BIBLIOTHEK_REF_ID = (SELECT ID FROM T_BIBLIOTHEK WHERE MARKE_REF_ID = 'AU');

UPDATE T_ARBEITSBEREICH SET MARKE_REF_ID = 'AU' WHERE ID = 1;
UPDATE T_ARBEITSBEREICH SET MARKE_REF_ID = 'VW' WHERE ID = 2;

UPDATE T_BENUTZER us SET us.DEFAULT_MARKE_REF_ID  = null;
UPDATE T_BENUTZER us SET us.DEFAULT_MARKE_REF_ID  = 
(SELECT ar.MARKE_REF_ID FROM T_ARBEITSBEREICH ar, T_REL_BENUTZER_ARBEITSBEREICH rel
WHERE rel.USER_ID_REF = us.USER_ID AND rel.ARBEITSBEREICH_REF = ar.ID 
and rel.USER_ID_REF in (select USER_ID_REF from T_REL_BENUTZER_ARBEITSBEREICH group by USER_ID_REF having count(USER_ID_REF) = 1) ) WHERE us.DEFAULT_MARKE_REF_ID is null;

UPDATE T_BENUTZER us set us.DEFAULT_BIBLIOTHEK_REF_ID  = null;
UPDATE T_BENUTZER us set us.DEFAULT_BIBLIOTHEK_REF_ID  = 
(SELECT lib.ID FROM T_BIBLIOTHEK lib
WHERE lib.MARKE_REF_ID = us.DEFAULT_MARKE_REF_ID  and rownum = 1) where us.DEFAULT_MARKE_REF_ID is not null and DEFAULT_BIBLIOTHEK_REF_ID is null;

COMMIT;