ALTER TABLE T_BENUTZER ADD ELEMENT_BESITZER_FILTER VARCHAR2(100 char) ;
ALTER TABLE T_BENUTZER ADD ELEMENT_NUTZER_FILTER VARCHAR2(100 char) ;
ALTER TABLE T_BENUTZER ADD BAUSTEIN_BESITZER_FILTER VARCHAR2(100 char) ;
ALTER TABLE T_BENUTZER ADD BAUSTEIN_NUTZER_FILTER VARCHAR2(100 char) ;