CREATE INDEX ORDENER_REF_OBJECT_TYP_I ON T_ORDNER (ORDNER_REF_ID, OBJEKT_TYP_REF_ID) PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
 
CREATE INDEX BIBLIOTHEK_REF_ID_I ON T_BAUSTEIN (BIBLIOTHEK_REF_ID) PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;

CREATE INDEX STAND_DATE_I ON T_BAUSTEINSTAND (STAND_DATE)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;

CREATE INDEX WERT_ART_DATUM_KB_I ON T_BAUSTEINVERSIONANDERUNG (ALTER_WERT, ART, DATUM, KB_STAND_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;

CREATE INDEX ART_DATUM_KB_I ON T_BAUSTEINVERSIONANDERUNG (ART, DATUM, KB_STAND_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
 
CREATE INDEX KBA_STAND_ID_I ON T_BAUSTEINVERSIONANDERUNG (KB_STAND_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;

CREATE INDEX ART_DATUM_KE_I ON T_ELEMENTVERSIONANDERUNG (ELEM_VER_REF_ID,ART, DATUM)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.index@;

CREATE INDEX RBN_MARKE_REF_I ON T_REL_BAUSVERSION_NUTZER (MARKE_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
 
CREATE INDEX BEN_MARKE_REF_I ON T_BENUTZER (DEFAULT_MARKE_REF_ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;

CREATE INDEX ELEMVERS_BENUT_FREI_I ON T_ELEMENTVERSION (FREIGABE_DURCH_REF_ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;  

CREATE INDEX KE_BESITZER_I ON T_ELEMENT (BESITZER) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;   
  
CREATE INDEX BIB_MARKE_REF_I ON T_BIBLIOTHEK (MARKE_REF_ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@; 
  
CREATE INDEX ARB_MARKE_REF_I ON T_ARBEITSBEREICH (MARKE_REF_ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;    
  
CREATE INDEX BAUSTEINVERS_BENUT_FRE_I ON T_BAUSTEINVERSION (FREIGABE_DURCH_REF_ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;    
  
CREATE INDEX BEN_BIBLIOTHEK_REF_I ON T_BENUTZER (DEFAULT_BIBLIOTHEK_REF_ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;   
  
CREATE INDEX BAUS_DOK_DOKUMENTPOOL_I ON T_REL_BAUSVERSION_DOKUMENTPOOL (ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;     

CREATE INDEX ELEM_NUTZER_MARKE_REF_I ON T_REL_ELEMVERSION_NUTZER (MARKE_REF_ID) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@;
  
CREATE INDEX KB_BESITZER_I ON T_BAUSTEIN (BESITZER) PCTFREE 10
  TABLESPACE @prop.application.db.tablespace.index@; 

CREATE INDEX KBA_DATUM_ANDERUNG_ART_I ON T_BAUSTEINVERSIONANDERUNG (KB_STAND_REF_ID,DATUM,ANDERUNG_ART)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 