DROP TABLE T_ARBEITSBEREICH CASCADE CONSTRAINTS;               
DROP TABLE T_BAUSTEIN CASCADE CONSTRAINTS;                     
DROP TABLE T_BAUSTEINKOSTEN CASCADE CONSTRAINTS;               
DROP TABLE T_BAUSTEINVERSION CASCADE CONSTRAINTS;              
DROP TABLE T_BENUTZER CASCADE CONSTRAINTS;                     
DROP TABLE T_DOKUMENTPOOL CASCADE CONSTRAINTS;                 
DROP TABLE T_ELEMENT CASCADE CONSTRAINTS;                      
DROP TABLE T_ELEMENTKATEGORIE CASCADE CONSTRAINTS;             
DROP TABLE T_ELEMENTVERSION CASCADE CONSTRAINTS;               
DROP TABLE T_ELEMENTWERTE CASCADE CONSTRAINTS;                 
DROP TABLE T_ENUM_BAUSTEINKLASSE CASCADE CONSTRAINTS;          
DROP TABLE T_ENUM_BAUSTEINTYP CASCADE CONSTRAINTS;             
DROP TABLE T_ENUM_INVESTANTEIL CASCADE CONSTRAINTS;            
DROP TABLE T_ENUM_OBJEKTTYP CASCADE CONSTRAINTS;               
DROP TABLE T_ENUM_STATUS CASCADE CONSTRAINTS;                  
DROP TABLE T_ENUM_TRANSITION CASCADE CONSTRAINTS;              
DROP TABLE T_KOSTENATTRIBUT CASCADE CONSTRAINTS;               
DROP TABLE T_LEISTUNGSINHALT CASCADE CONSTRAINTS;              
DROP TABLE T_ORDNER CASCADE CONSTRAINTS;                       
DROP TABLE T_PLANKOSTENKATEGORIE CASCADE CONSTRAINTS;          
DROP TABLE T_RECHT CASCADE CONSTRAINTS;                        
DROP TABLE T_REL_BAUSTEIN_ELEMENT CASCADE CONSTRAINTS;         
DROP TABLE T_REL_BAUSVERSION_DOKUMENTPOOL CASCADE CONSTRAINTS; 
DROP TABLE T_REL_BENUTZER_ARBEITSBEREICH CASCADE CONSTRAINTS;  
DROP TABLE T_REL_BENUTZER_ROLLEN CASCADE CONSTRAINTS;          
DROP TABLE T_REL_ELEMVERSION_DOKUMENTPOOL CASCADE CONSTRAINTS; 
DROP TABLE T_REL_ROLLEN_RECHT CASCADE CONSTRAINTS;             
DROP TABLE T_REL_ROLLEN_ROLLEN CASCADE CONSTRAINTS;            
DROP TABLE T_ROLLEN CASCADE CONSTRAINTS;                       
DROP TABLE T_STDSATZKATALOG CASCADE CONSTRAINTS;               
DROP TABLE T_STUNDENSAETZE CASCADE CONSTRAINTS;
DROP TABLE T_ELEMENTVERSIONANDERUNG CASCADE constraints;
DROP TABLE T_BAUSTEINVERSIONANDERUNG CASCADE constraints;

DROP SEQUENCE SEQ_COMPONENT;                  
DROP SEQUENCE SEQ_COMPONENT_CLASS;            
DROP SEQUENCE SEQ_COMPONENT_COST;             
DROP SEQUENCE SEQ_COMPONENT_ELEMENT;          
DROP SEQUENCE SEQ_COMPONENT_TYPE;             
DROP SEQUENCE SEQ_COMPONENT_VERSION;          
DROP SEQUENCE SEQ_COST_ATTRIBUTE;             
DROP SEQUENCE SEQ_COST_PLAN_CATEGORY;         
DROP SEQUENCE SEQ_DOCUMENT_POOL;              
DROP SEQUENCE SEQ_EFFORT_CONTENT;             
DROP SEQUENCE SEQ_ELEMENT;                    
DROP SEQUENCE SEQ_ELEMENT_CATEGORY;           
DROP SEQUENCE SEQ_ELEMENT_VALUE;              
DROP SEQUENCE SEQ_ELEMENT_VERSION;            
DROP SEQUENCE SEQ_FOLDER;                     
DROP SEQUENCE SEQ_HOURLY_RATE;                
DROP SEQUENCE SEQ_HOURLY_RATE_CATALOG;        
DROP SEQUENCE SEQ_INVESTMENT_PART;            
DROP SEQUENCE SEQ_OBJECT_TYPE;                
DROP SEQUENCE SEQ_RIGHT;                      
DROP SEQUENCE SEQ_ROLE;                       
DROP SEQUENCE SEQ_USER;                       
DROP SEQUENCE SEQ_WORK_AREA; 
DROP SEQUENCE SEQ_ELEMENT_VERSION_ANDERUNG;
DROP SEQUENCE SEQ_BAUSTEIN_VERSION_ANDERUNG;

PROMPT Creating Sequence 'seq_component';
CREATE SEQUENCE seq_component
 INCREMENT BY 1
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;
PROMPT Creating Sequence 'seq_component_class';
CREATE SEQUENCE seq_component_class
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_component_cost';
CREATE SEQUENCE seq_component_cost
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE;
PROMPT Creating Sequence 'seq_component_element';
CREATE SEQUENCE seq_component_element
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_component_type';
CREATE SEQUENCE seq_component_type
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;
PROMPT Creating Sequence 'seq_component_version';
CREATE SEQUENCE seq_component_version
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_cost_attribute';
CREATE SEQUENCE seq_cost_attribute
 INCREMENT BY 1 
 START WITH 1
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;
PROMPT Creating Sequence 'seq_cost_plan_category';
CREATE SEQUENCE seq_cost_plan_category
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;
PROMPT Creating Sequence 'seq_document_pool';
CREATE SEQUENCE seq_document_pool
 INCREMENT BY 1 
 START WITH 1
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_effort_content';
CREATE SEQUENCE seq_effort_content
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_element';
CREATE SEQUENCE seq_element
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_element_category';
CREATE SEQUENCE seq_element_category
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_element_value';
CREATE SEQUENCE seq_element_value
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_element_version';
CREATE SEQUENCE seq_element_version
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_folder';
CREATE SEQUENCE seq_folder 
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_hourly_rate';
CREATE SEQUENCE seq_hourly_rate
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_hourly_rate_catalog';
CREATE SEQUENCE seq_hourly_rate_catalog
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_investment_part';
CREATE SEQUENCE seq_investment_part 
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_object_type';
CREATE SEQUENCE seq_object_type 
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_right';
CREATE SEQUENCE seq_right 
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_role';
CREATE SEQUENCE seq_role 
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_user';
CREATE SEQUENCE seq_user 
 INCREMENT BY 1 
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE 
 NOCYCLE;
PROMPT Creating Sequence 'seq_work_area';
CREATE SEQUENCE seq_work_area 
INCREMENT BY 1 
START WITH 1
NOMAXVALUE 
NOMINVALUE 
NOCYCLE;
PROMPT Creating Sequence 'SEQ_ELEMENT_VERSION_ANDERUNG';
CREATE SEQUENCE SEQ_ELEMENT_VERSION_ANDERUNG 
INCREMENT BY 1 
START WITH 1
NOMAXVALUE 
NOMINVALUE 
NOCYCLE;
PROMPT Creating Sequence 'SEQ_BAUSTEIN_VERSION_ANDERUNG';
CREATE SEQUENCE SEQ_BAUSTEIN_VERSION_ANDERUNG 
INCREMENT BY 1 
START WITH 1
NOMAXVALUE 
NOMINVALUE 
NOCYCLE;

PROMPT Creating Table 'T_ARBEITSBEREICH';
create table T_ARBEITSBEREICH
 (ID number(19,0) not null
 , BEZEICHNUNG varchar2(50 char) not null
 , BESCHREIBUNG varchar2(4000 char)
 )
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_BAUSTEIN';
create table T_BAUSTEIN
(ID number(19,0) not null
, UUIDKB varchar2(1024 char)
, BAUSTEIN_NR varchar2(256 char) not null
, BEZEICHNUNG varchar2(256 char) not null
, X_INAKTIV number(1,0) not null
, ERSTELLER_REF_ID number(19,0) not null
, ERSTELLT_AM DATE not null
, GEAENDERT_VON_REF_ID number(19,0)
, GEAENDERT_AM DATE, INAKTIV_VON DATE
, ORDNER_REF_ID number(19,0)
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_BAUSTEINKOSTEN';
create table T_BAUSTEINKOSTEN
(ID number(19,0) not null
, ANZAHL number(19,2)
, BETRAG number(19,2)
, BESCHREIBUNG varchar2(255 char)
, KOSTEN_ATTRIBUT_REF_ID number(19,0)
, KB_REF_UU_ID number(19,0)
) 
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_BAUSTEINVERSION';
create table T_BAUSTEINVERSION
(KB_VERSION_UU_ID number(19,0) not null
, BESCHREIBUNG varchar2(2048 char)
, MECHANIK_KONSTRUKTION varchar2(4000 char)
, MECHANIK_AUSFUEHRUNG varchar2(4000 char)
, ELEKTRIK varchar2(4000 char)
, BEMERKUNGEN varchar2(4000 char)
, GUELTIG_VON DATE not null
, GUELTIG_BIS DATE not null
, ABBILDUNG blob
, ERSTELLT_AM DATE not null
, GEAENDERT_AM DATE
, BEISTELLUNG_AG number(1,0) not null
, E_PREISSTAND_DATUM DATE
, E_PREISSTAND_BEMERKUNG varchar2(300 char)
, M_PREISSTAND_DATUM DATE
, M_PREISSTAND_BEMERKUNG varchar2(300 char)
, KATALOG_NUMMER varchar2(300 char)
, HERSTELLER varchar2(300 char)
, ERSTELLER_REF_ID number(19,0)
, GEAENDERT_VON_REF_ID number(19,0)
, KB_REF_UU_ID number(19,0)
, FREIGABE_DURCH_REF_ID number(19,0)
, ENUM_BAUSTEIN_KLASSE_REF_ID number(19,0)
, ENUM_STATUS_REF_ID number(19,0)
, ENUM_BAUSTEIN_TYP_REF_ID number(19,0)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@
LOB (ABBILDUNG) STORE AS (TABLESPACE @prop.application.db.tablespace.lob@);

PROMPT Creating Table 'T_BENUTZER'; 
create table T_BENUTZER 
(USER_ID number(19,0) not null
, NACHNAME varchar2(50 char) not null
, VORNAME varchar2(50 char)
, KUMS_USER_ID varchar2(10 char) not null
, EMAIL varchar2(50 char)
, TELEFON varchar2(20 char)
, ANREDE varchar2(20 char)
, DEFAULT_STD_SATZ_KAT_REF_ID number(19,0)
, STATUS_ELEMENT_FREIGEGEBEN number(1,0)
,AKTIV number(1,0) not null
, BENUTZER_ADMIN_ARBEITS varchar2(100 char)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_DOKUMENTPOOL'; 
create table T_DOKUMENTPOOL 
(ID number(19,0) not null
, PFAD varchar2(255 char) not null
, content blob not null
, BESCHREIBUNG varchar2(255 char)
, DATEI_TYP varchar2(100 char)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@
LOB (content) STORE AS (TABLESPACE @prop.application.db.tablespace.lob@);

PROMPT Creating Table 'T_ELEMENT';
create table T_ELEMENT 
(UUIDKE number(19,0) not null
, ELEMENT_NR varchar2(10 char) not null
, BEZEICHNUNG varchar2(255 char) not null
, X_INAKTIV number(1,0) not null
, ERSTELLER_REF_ID number(19,0)
, ERSTELLT_AM DATE not null
, GEAENDERT_VON_REF_ID number(19,0)
, GEAENDERT_AM DATE
, INAKTIV_VON DATE
, ORDNER_REF_ID number(19,0)
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ELEMENTKATEGORIE';
create table T_ELEMENTKATEGORIE 
(ID number(19,0) not null
, BEZEICHNUNG varchar2(50 char) not null
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ELEMENTVERSION';
create table T_ELEMENTVERSION
(UUIDKEVERSION number(19,0) not null
, BESCHREIBUNG varchar2(1000 char)
, MECHANIK_KONSTRUKTION varchar2(4000 char)
, MECHANIK_AUSFUEHRUNG varchar2(4000 char)
, ELEKTRIK varchar2(4000 char)
, BEMERKUNGEN varchar2(4000 char)
, GUELTIG_VON DATE not null
, GUELTIG_BIS DATE not null
, ERSTELLT_AM DATE not null
, GEAENDERT_AM DATE
, BEISTELLUNG_AG number(1,0) not null
, E_PREISSTAND_DATUM DATE
, E_PREISSTAND_BEMERKUNG varchar2(300 char)
, M_PREISSTAND_DATUM DATE
, M_PREISSTAND_BEMERKUNG varchar2(300 char)
, KATALOG_NUMMER varchar2(300 char)
, HERSTELLER varchar2(300 char)
, ERSTELLER_REF_ID number(19,0)
, GEAENDERT_VON_REF_ID number(19,0)
, KE_REF_UU_ID number(19,0)
, FREIGABE_DURCH_REF_ID number(19,0)
, ENUM_STATUS_REF_ID number(19,0)
, KATEGORIE_REF_ID number(19,0)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ELEMENTWERTE';
create table T_ELEMENTWERTE 
(ID number(19,0) not null
, ANZAHL number(19,2)
, BETRAG number(19,2)
, BESCHREIBUNG varchar2(255 char)
, ELEM_VER_REF_ID number(19,0)
, KOSTEN_ATTRIBUT_REF_ID number(19,0)
) 
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ENUM_BAUSTEINKLASSE';
create table T_ENUM_BAUSTEINKLASSE 
(ID number(19,0) not null
, BAUSTEIN_KLASSE varchar2(50 char) not null
) 
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ENUM_BAUSTEINTYP';
create table T_ENUM_BAUSTEINTYP 
(ID number(19,0) not null
, BAUSTEIN_TYP varchar2(256 char) not null
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ENUM_INVESTANTEIL';
create table T_ENUM_INVESTANTEIL 
(ID number(19,0) not null
, INVESTITIONS_ANTEIL varchar2(50 char) not null
, KATEGORIE varchar2(50 char) not null
, ORDER_NR number(10,0)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ENUM_OBJEKTTYP';
create table T_ENUM_OBJEKTTYP 
(ID number(19,0) not null
, OBJEKT_TYP varchar2(150 char) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ENUM_STATUS';
create table T_ENUM_STATUS (ID number(19,0) not null
, BEZEICHNUNG varchar2(25 char)
, READ_ONLY NUMBER default 1 not null
, ADD_ALLOWED NUMBER default 1 not null
, SAVE_ALLOWED NUMBER default 1 not null
, DELETE_ALLOWED NUMBER default 1 not null
, BACK_ALLOWED NUMBER default 1 not null
, PRINT_ALLOWED NUMBER default 1 not null
, EXPORT_ALLOWED NUMBER default 1 not null
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ENUM_TRANSITION';
create table T_ENUM_TRANSITION 
(VON_STATUS number(19,0) not null
, ZUR_STATUS number(19,0) not null
, BEZEICHNUNG varchar2(25 char)
, BATCH NUMBER default 1 not null
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_KOSTENATTRIBUT';
create table T_KOSTENATTRIBUT 
(ID number(19,0) not null
, BEZEICHNUNG varchar2(256 char)
, BESCHREIBUNG varchar2(255 char)
, EINHEIT varchar2(10 char) not null
, X_PREIS_PRO_EINHEIT NUMBER default 1 not null
, ORDER_NR number(10,0)
, BEISTELLUNG_AG NUMBER default 1 not null
, PLAN_KOSTEN_KATEGORIE_REF number(19,0)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_LEISTUNGSINHALT';
create table T_LEISTUNGSINHALT 
(ID number(19,0) not null
, MECHANIK_KONSTRUKTION varchar2(4000 char) not null
, MECHANIK_AUSFUEHRUNG varchar2(4000 char) not null
, ELEKTRIK varchar2(4000 char) not null
, BEMERKUNG varchar2(4000 char) not null
, X_DEFAULT_LEISTUNGSINHALT number(1,0) not null
, ENUM_OBJ_REF_ID number(19,0)
, OBJ_VER_REF_ID number(19,0)
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ORDNER';
create table T_ORDNER (ID number(19,0) not null
, UUIDORDNER varchar2(1024 char)
, BEZEICHNUNG varchar2(100 char) not null
, ORDNER_REF_ID number(19,0)
, OBJEKT_TYP_REF_ID number(19,0)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_PLANKOSTENKATEGORIE';
create table T_PLANKOSTENKATEGORIE 
(ID number(19,0) not null
, PLAN_KOSTEN_KATEGORIE varchar2(255 char) not null
, ORDER_NR number(10,0)
, BEISTELLUNG_AG NUMBER default 1 not null
, T_ENUM_INVESTANTEIL_REF number(19,0)
) PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_RECHT';
create table T_RECHT 
(RECHT_ID number(19,0) not null
, KODE varchar2(30 char) not null
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_REL_BAUSTEIN_ELEMENT';
create table T_REL_BAUSTEIN_ELEMENT 
(ID number(19,0) not null
, ANZAHL number(19,0)
, KE_REF_UU_ID number(19,0)
, KBVERSIONREFUUID number(19,0)
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_REL_BAUSVERSION_DOKUMENTPOOL';
create table T_REL_BAUSVERSION_DOKUMENTPOOL 
(KB_VERSION_UU_ID number(19,0) not null
, ID number(19,0) not null
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_REL_BENUTZER_ARBEITSBEREICH';
create table T_REL_BENUTZER_ARBEITSBEREICH 
(USER_ID_REF number(19,0) not null
, ARBEITSBEREICH_REF number(19,0) not null
) 
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_REL_BENUTZER_ROLLEN';
create table T_REL_BENUTZER_ROLLEN 
(USER_REF_ID number(19,0) not null
, ROLLE_REF_ID number(19,0) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_REL_ELEMVERSION_DOKUMENTPOOL';
create table T_REL_ELEMVERSION_DOKUMENTPOOL 
(UUIDKEVERSION_REF_ID number(19,0) not null
, ID number(19,0) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_REL_ROLLEN_RECHT';
create table T_REL_ROLLEN_RECHT 
(ROLLEN_ID_REF number(19,0) not null
, RECHT_ID_REF number(19,0) not null
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_REL_ROLLEN_ROLLEN';
create table T_REL_ROLLEN_ROLLEN 
(ROLLEN_ID_REF number(19,0) not null
, MANAGED_ROLLEN_ID_REF number(19,0) not null
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ROLLEN';
create table T_ROLLEN 
(ID number(19,0) not null
, BEZEICHNUNG varchar2(50 char) not null
, BESCHREIBUNG varchar2(255 char)
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_STDSATZKATALOG';
create table T_STDSATZKATALOG 
(ID number(19,0) not null
, BEZEICHNUNG varchar2(50 char) not null
, BESCHREIBUNG varchar2(255 char)
, ERSTELLER_REF_ID number(19,0) not null
, ERSTELLT_AM DATE not null
, GEAENDERT_VON_REF_ID number(19,0)
, GEAENDERT_AM DATE, WORK_AREA_ID number(19,0)
, ORDNER_REF_ID number(19,0)
)
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_STUNDENSAETZE';
create table T_STUNDENSAETZE 
(ID number(19,0) not null
, WERT number(19,2)
, KOSTEN_ATTRIBUT_REF_ID number(19,0)
, STD_SATZ_KAT_REF_ID number(19,0)
)
PCTFREE 10 
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_ELEMENTVERSIONANDERUNG';
create table T_ELEMENTVERSIONANDERUNG 
(ANDERUNG_ID number(19,0) not null
, ANDERUNG varchar2(300 char)
, ALTER_WERT varchar2(4000 char)
, NEUER_WERT varchar2(4000 char)
, DATUM DATE not null
, lANG NUMBER not null
, ART varchar2(100 char) not null
, BENUTZER varchar2(150 char)
, ELEM_VER_REF_ID number(19,0))
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Table 'T_BAUSTEINVERSIONANDERUNG';
create table T_BAUSTEINVERSIONANDERUNG 
(ANDERUNG_ID number(19,0) not null
, ANDERUNG varchar2(300 char)
, ALTER_WERT varchar2(4000 char)
, NEUER_WERT varchar2(4000 char)
, DATUM DATE not null
, lANG NUMBER not null
, ART varchar2(100 char) not null
, BENUTZER varchar2(150 char)
, KB_VERSION_ID number(19,0))
PCTFREE 10
TABLESPACE @prop.application.db.tablespace.table@;

PROMPT Creating Primary Key on 'T_ARBEITSBEREICH';
ALTER TABLE T_ARBEITSBEREICH
 ADD (CONSTRAINT T_ARBEITSBEREICH_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_BAUSTEIN';
ALTER TABLE T_BAUSTEIN
 ADD (CONSTRAINT T_BAUSTEIN_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_BAUSTEINKOSTEN';
ALTER TABLE T_BAUSTEINKOSTEN
 ADD (CONSTRAINT T_BAUSTEINKOSTEN_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION
 ADD (CONSTRAINT T_BAUSTEINVERSION_PK PRIMARY KEY 
  (KB_VERSION_UU_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_BENUTZER';
ALTER TABLE T_BENUTZER
 ADD (CONSTRAINT T_BENUTZER_PK PRIMARY KEY 
  (USER_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_DOKUMENTPOOL';
ALTER TABLE T_DOKUMENTPOOL
 ADD (CONSTRAINT T_DOKUMENTPOOL_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ELEMENT';
ALTER TABLE T_ELEMENT
 ADD (CONSTRAINT T_ELEMENT_PK PRIMARY KEY 
  (UUIDKE)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ELEMENTKATEGORIE';
ALTER TABLE T_ELEMENTKATEGORIE
 ADD (CONSTRAINT T_ELEMENTKATEGORIE_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ELEMENTVERSION';
ALTER TABLE T_ELEMENTVERSION
 ADD (CONSTRAINT T_ELEMENTVERSION_PK PRIMARY KEY 
  (UUIDKEVERSION)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ELEMENTWERTE';
ALTER TABLE T_ELEMENTWERTE
 ADD (CONSTRAINT T_ELEMENTWERTE_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ENUM_BAUSTEINKLASSE';
ALTER TABLE T_ENUM_BAUSTEINKLASSE
 ADD (CONSTRAINT T_ENUM_BAUSTEINKLASSE_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ENUM_BAUSTEINTYP';
ALTER TABLE T_ENUM_BAUSTEINTYP
 ADD (CONSTRAINT T_ENUM_BAUSTEINTYP_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ENUM_INVESTANTEIL';
ALTER TABLE T_ENUM_INVESTANTEIL
 ADD (CONSTRAINT T_ENUM_INVESTANTEIL_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ENUM_OBJEKTTYP';
ALTER TABLE T_ENUM_OBJEKTTYP
 ADD (CONSTRAINT T_ENUM_OBJEKTTYP_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ENUM_STATUS';
ALTER TABLE T_ENUM_STATUS
 ADD (CONSTRAINT T_ENUM_STATUS_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ENUM_TRANSITION';
ALTER TABLE T_ENUM_TRANSITION
 ADD (CONSTRAINT T_ENUM_TRANSITION_PK PRIMARY KEY 
  (VON_STATUS,ZUR_STATUS)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_KOSTENATTRIBUT';
ALTER TABLE T_KOSTENATTRIBUT
 ADD (CONSTRAINT T_KOSTENATTRIBUT_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_LEISTUNGSINHALT';
ALTER TABLE T_LEISTUNGSINHALT
 ADD (CONSTRAINT T_LEISTUNGSINHALT_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ORDNER';
ALTER TABLE T_ORDNER
 ADD (CONSTRAINT T_ORDNER_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_PLANKOSTENKATEGORIE';
ALTER TABLE T_PLANKOSTENKATEGORIE
 ADD (CONSTRAINT T_PLANKOSTENKATEGORIE_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_RECHT';
ALTER TABLE T_RECHT
 ADD (CONSTRAINT T_RECHT_PK PRIMARY KEY 
  (RECHT_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_REL_BAUSTEIN_ELEMENT';
ALTER TABLE T_REL_BAUSTEIN_ELEMENT
 ADD (CONSTRAINT T_REL_BAUSTEIN_ELEMENT_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_REL_BAUSVERSION_DOKUMENTPOOL';
ALTER TABLE T_REL_BAUSVERSION_DOKUMENTPOOL
 ADD (CONSTRAINT T_REL_BAUSVERSION_DOKPOOL_PK PRIMARY KEY 
  (KB_VERSION_UU_ID,ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_REL_BENUTZER_ARBEITSBEREICH';
ALTER TABLE T_REL_BENUTZER_ARBEITSBEREICH
 ADD (CONSTRAINT T_REL_BENUTZER_ARBEIT_PK PRIMARY KEY 
  (USER_ID_REF,ARBEITSBEREICH_REF)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_REL_BENUTZER_ROLLEN';
ALTER TABLE T_REL_BENUTZER_ROLLEN
 ADD (CONSTRAINT T_REL_BENUTZER_ROLLEN_PK PRIMARY KEY 
  (USER_REF_ID,ROLLE_REF_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_REL_ELEMVERSION_DOKUMENTPOOL';
ALTER TABLE T_REL_ELEMVERSION_DOKUMENTPOOL
 ADD (CONSTRAINT T_REL_ELEMVERSION_DOKPOOL_PK PRIMARY KEY 
  (UUIDKEVERSION_REF_ID,ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_REL_ROLLEN_RECHT';
ALTER TABLE T_REL_ROLLEN_RECHT
 ADD (CONSTRAINT T_REL_ROLLEN_RECHT_PK PRIMARY KEY 
  (ROLLEN_ID_REF,RECHT_ID_REF)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_REL_ROLLEN_ROLLEN';
ALTER TABLE T_REL_ROLLEN_ROLLEN
 ADD (CONSTRAINT T_REL_ROLLEN_ROLLEN_PK PRIMARY KEY 
  (ROLLEN_ID_REF,MANAGED_ROLLEN_ID_REF)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ROLLEN';
ALTER TABLE T_ROLLEN
 ADD (CONSTRAINT T_ROLLEN_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_STDSATZKATALOG';
ALTER TABLE T_STDSATZKATALOG
 ADD (CONSTRAINT T_STDSATZKATALOG_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_STUNDENSAETZE';
ALTER TABLE T_STUNDENSAETZE
 ADD (CONSTRAINT T_STUNDENSAETZE_PK PRIMARY KEY 
  (ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_ELEMENTVERSIONANDERUNG';
ALTER TABLE T_ELEMENTVERSIONANDERUNG
 ADD (CONSTRAINT T_ELEMENTVERSIONANDERUNG_PK PRIMARY KEY 
  (ANDERUNG_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Primary Key on 'T_BAUSTEINVERSIONANDERUNG';
ALTER TABLE T_BAUSTEINVERSIONANDERUNG
 ADD (CONSTRAINT T_BAUSTEINVERSIONANDERUNG_PK PRIMARY KEY 
  (ANDERUNG_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
 
PROMPT Creating Foreign Key on 'T_BAUSTEIN';
ALTER TABLE T_BAUSTEIN ADD (CONSTRAINT
BAUSTEIN_ORDNER_FK FOREIGN KEY
 (ORDNER_REF_ID) REFERENCES T_ORDNER 
 (ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINKOSTEN';
ALTER TABLE T_BAUSTEINKOSTEN ADD (CONSTRAINT
 BAUSTEINKOST_BAUSTEINVER_FK FOREIGN KEY
 (KB_REF_UU_ID) REFERENCES T_BAUSTEINVERSION
 (KB_VERSION_UU_ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINKOSTEN';
ALTER TABLE T_BAUSTEINKOSTEN ADD (CONSTRAINT
 BAUSTEINKOST_KOSTENATT_FK FOREIGN KEY
 (KOSTEN_ATTRIBUT_REF_ID) REFERENCES T_KOSTENATTRIBUT
 (ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION ADD (CONSTRAINT
 BAUST_VERS_BAUSTEIN_KLASS_FK FOREIGN KEY
 (ENUM_BAUSTEIN_KLASSE_REF_ID) REFERENCES T_ENUM_BAUSTEINKLASSE
 (ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION ADD (CONSTRAINT
 BAUSTEINVERSION_BAUSTEIN_FK FOREIGN KEY
 (KB_REF_UU_ID) REFERENCES T_BAUSTEIN
 (ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION ADD (CONSTRAINT
 BAUSTEINVERS_BAUSTEINTYP_FK FOREIGN KEY
 (ENUM_BAUSTEIN_TYP_REF_ID) REFERENCES T_ENUM_BAUSTEINTYP
 (ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION ADD (CONSTRAINT
 BAUSTEINVERS_BENUTZER_GEA_FK FOREIGN KEY
 (GEAENDERT_VON_REF_ID) REFERENCES T_BENUTZER
 (USER_ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION ADD (CONSTRAINT
 BAUSTEINVERS_BENUT_ERST_FK FOREIGN KEY
 (ERSTELLER_REF_ID) REFERENCES T_BENUTZER
 (USER_ID));
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION ADD (CONSTRAINT
 BAUSTEINVERS_BENUT_FREI_FK FOREIGN KEY
 (FREIGABE_DURCH_REF_ID) REFERENCES T_BENUTZER
 (USER_ID)); 
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSION';
ALTER TABLE T_BAUSTEINVERSION ADD (CONSTRAINT
 BAUSTEINVERS_STATUS_FK FOREIGN KEY
 (ENUM_STATUS_REF_ID) REFERENCES T_ENUM_STATUS
 (ID));
PROMPT Creating Foreign Key on 'T_ELEMENT';
ALTER TABLE T_ELEMENT ADD (CONSTRAINT 
 ELEMENT_ORDNER_FK FOREIGN KEY
 (ORDNER_REF_ID) REFERENCES T_ORDNER
 (ID));
PROMPT Creating Foreign Key on 'T_ELEMENTVERSION';
ALTER TABLE T_ELEMENTVERSION ADD (CONSTRAINT
 ELEMVERS_ELEMKATEG_FK FOREIGN KEY
 (KATEGORIE_REF_ID) REFERENCES T_ELEMENTKATEGORIE
 (ID));
PROMPT Creating Foreign Key on 'T_ELEMENTVERSION';
ALTER TABLE T_ELEMENTVERSION ADD (CONSTRAINT
 ELEMVERS_ELEMENT_FK FOREIGN KEY
 (KE_REF_UU_ID) REFERENCES T_ELEMENT
 (UUIDKE));
PROMPT Creating Foreign Key on 'T_ELEMENTVERSION';
ALTER TABLE T_ELEMENTVERSION ADD (CONSTRAINT
 ELEMVERS_BENUTZER_GEA_FK FOREIGN KEY
 (GEAENDERT_VON_REF_ID) REFERENCES T_BENUTZER
 (USER_ID));
PROMPT Creating Foreign Key on 'T_ELEMENTVERSION';
ALTER TABLE T_ELEMENTVERSION ADD (CONSTRAINT
 ELEMVERS_BENUT_ERST_ID_FK FOREIGN KEY
 (ERSTELLER_REF_ID) REFERENCES T_BENUTZER
 (USER_ID));
PROMPT Creating Foreign Key on 'T_ELEMENTVERSION';
ALTER TABLE T_ELEMENTVERSION ADD (CONSTRAINT
 ELEMVERS_BENUT_FREI_ID_FK FOREIGN KEY
 (FREIGABE_DURCH_REF_ID) REFERENCES T_BENUTZER
 (USER_ID)); 
PROMPT Creating Foreign Key on 'T_ELEMENTVERSION';
ALTER TABLE T_ELEMENTVERSION ADD (CONSTRAINT
 ELEMVERS_STATUS_FK FOREIGN KEY
 (ENUM_STATUS_REF_ID) REFERENCES
 T_ENUM_STATUS (ID));
PROMPT Creating Foreign Key on 'T_ELEMENTWERTE';
ALTER TABLE T_ELEMENTWERTE ADD (CONSTRAINT
 ELEMENTWERTE_ELEMVERS_FK FOREIGN KEY
 (ELEM_VER_REF_ID) REFERENCES T_ELEMENTVERSION
 (UUIDKEVERSION));
PROMPT Creating Foreign Key on 'T_ELEMENTWERTE';
ALTER TABLE T_ELEMENTWERTE ADD (CONSTRAINT
 ELEMENTWERTE_KOST_ATTR_FK FOREIGN KEY
 (KOSTEN_ATTRIBUT_REF_ID) REFERENCES T_KOSTENATTRIBUT
 (ID));
PROMPT Creating Foreign Key on 'T_ENUM_TRANSITION';
ALTER TABLE T_ENUM_TRANSITION ADD (CONSTRAINT
 TRANSITION_ZUR_STATUS_FK FOREIGN KEY
 (ZUR_STATUS) REFERENCES T_ENUM_STATUS
 (ID));
PROMPT Creating Foreign Key on 'T_ENUM_TRANSITION';
ALTER TABLE T_ENUM_TRANSITION ADD (CONSTRAINT
 TRANSITION_VON_STATUS_FK FOREIGN KEY
 (VON_STATUS) REFERENCES T_ENUM_STATUS
 (ID));
PROMPT Creating Foreign Key on 'T_KOSTENATTRIBUT';
ALTER TABLE T_KOSTENATTRIBUT ADD (CONSTRAINT
 KOSTENATTR_PLANKOSTEN_KAT_FK FOREIGN KEY
 (PLAN_KOSTEN_KATEGORIE_REF) REFERENCES T_PLANKOSTENKATEGORIE
 (ID));
PROMPT Creating Foreign Key on 'T_ORDNER';
ALTER TABLE T_ORDNER ADD (CONSTRAINT
 ORDNER_OBJEKTTYP_FK FOREIGN KEY
 (OBJEKT_TYP_REF_ID) REFERENCES T_ENUM_OBJEKTTYP
 (ID));
PROMPT Creating Foreign Key on 'T_ORDNER';
ALTER TABLE T_ORDNER ADD (CONSTRAINT
 ORDNER_ORDNER_FK FOREIGN KEY
 (ORDNER_REF_ID) REFERENCES T_ORDNER
 (ID));
PROMPT Creating Foreign Key on 'T_PLANKOSTENKATEGORIE';
ALTER TABLE T_PLANKOSTENKATEGORIE ADD (CONSTRAINT
 PLAN_KOST_INVESTANT_FK FOREIGN KEY
 (T_ENUM_INVESTANTEIL_REF) REFERENCES T_ENUM_INVESTANTEIL
 (ID));
PROMPT Creating Foreign Key on 'T_REL_BAUSTEIN_ELEMENT';
ALTER TABLE T_REL_BAUSTEIN_ELEMENT ADD (CONSTRAINT
 REL_BE_ELEMENT_FK FOREIGN KEY 
 (KE_REF_UU_ID) REFERENCES T_ELEMENT 
 (UUIDKE));
PROMPT Creating Foreign Key on 'T_REL_BAUSTEIN_ELEMENT';
ALTER TABLE T_REL_BAUSTEIN_ELEMENT ADD (CONSTRAINT
 REL_BE_BAUSTEINVERSION_FK FOREIGN KEY 
 (KBVERSIONREFUUID) REFERENCES T_BAUSTEINVERSION 
 (KB_VERSION_UU_ID));
PROMPT Creating Foreign Key on 'T_REL_BAUSVERSION_DOKUMENTPOOL';
ALTER TABLE T_REL_BAUSVERSION_DOKUMENTPOOL ADD (CONSTRAINT
 REL_BAUS_DOK_BAUSTEINVER_FK FOREIGN KEY
 (KB_VERSION_UU_ID) REFERENCES T_BAUSTEINVERSION
 (KB_VERSION_UU_ID));
PROMPT Creating Foreign Key on 'T_REL_BAUSVERSION_DOKUMENTPOOL';
ALTER TABLE T_REL_BAUSVERSION_DOKUMENTPOOL ADD (CONSTRAINT
 REL_BAUS_DOK_DOKUMENTPOOL_FK FOREIGN KEY
 (ID) REFERENCES T_DOKUMENTPOOL 
 (ID));
PROMPT Creating Foreign Key on 'T_REL_BENUTZER_ARBEITSBEREICH';
ALTER TABLE T_REL_BENUTZER_ARBEITSBEREICH ADD (CONSTRAINT 
 REL_BEN_ARB_ARBEITS_FK FOREIGN KEY
 (ARBEITSBEREICH_REF) REFERENCES T_ARBEITSBEREICH
 (ID));
PROMPT Creating Foreign Key on 'T_REL_BENUTZER_ARBEITSBEREICH';
ALTER TABLE T_REL_BENUTZER_ARBEITSBEREICH ADD (CONSTRAINT
 REL_BEN_ARB_BENUTZER_FK FOREIGN KEY
 (USER_ID_REF) REFERENCES T_BENUTZER
 (USER_ID));
PROMPT Creating Foreign Key on 'T_REL_BENUTZER_ROLLEN';
ALTER TABLE T_REL_BENUTZER_ROLLEN ADD (CONSTRAINT
 REL_BEN_ROLLEN_ROLLEN_FK FOREIGN KEY
 (ROLLE_REF_ID) REFERENCES T_ROLLEN
 (ID));
PROMPT Creating Foreign Key on 'T_REL_BENUTZER_ROLLEN';
ALTER TABLE T_REL_BENUTZER_ROLLEN ADD (CONSTRAINT
 REL_BEN_ROLLEN_BENUTZER_FK FOREIGN KEY
 (USER_REF_ID) REFERENCES T_BENUTZER
 (USER_ID));
PROMPT Creating Foreign Key on 'T_REL_ELEMVERSION_DOKUMENTPOOL';
ALTER TABLE T_REL_ELEMVERSION_DOKUMENTPOOL ADD (CONSTRAINT
 REL_ELEM_DOK_ELEMVERS_FK FOREIGN KEY
 (UUIDKEVERSION_REF_ID) REFERENCES T_ELEMENTVERSION
 (UUIDKEVERSION));
PROMPT Creating Foreign Key on 'T_REL_ELEMVERSION_DOKUMENTPOOL';
ALTER TABLE T_REL_ELEMVERSION_DOKUMENTPOOL ADD (CONSTRAINT
 REL_ELEM_DOK_DOK_FK FOREIGN KEY
 (ID) REFERENCES T_DOKUMENTPOOL
 (ID));
PROMPT Creating Foreign Key on 'T_REL_ROLLEN_RECHT';
ALTER TABLE T_REL_ROLLEN_RECHT ADD (CONSTRAINT
 REL_ROLLEN_RECHT_ROLL_FK FOREIGN KEY
 (ROLLEN_ID_REF) REFERENCES T_ROLLEN
 (ID));
PROMPT Creating Foreign Key on 'T_REL_ROLLEN_RECHT';
ALTER TABLE T_REL_ROLLEN_RECHT ADD (CONSTRAINT
 REL_ROLLEN_RECHT_RECHT_FK FOREIGN KEY
 (RECHT_ID_REF) REFERENCES T_RECHT
 (RECHT_ID));
PROMPT Creating Foreign Key on 'T_REL_ROLLEN_ROLLEN';
ALTER TABLE T_REL_ROLLEN_ROLLEN ADD (CONSTRAINT
 REL_ROLLEN_ROLLEN_ROLL_FK FOREIGN KEY
 (ROLLEN_ID_REF) REFERENCES T_ROLLEN
 (ID));
PROMPT Creating Foreign Key on 'T_REL_ROLLEN_ROLLEN';
ALTER TABLE T_REL_ROLLEN_ROLLEN ADD (CONSTRAINT
 REL_ROLLEN_ROLLEN_MANAG_FK FOREIGN KEY
 (MANAGED_ROLLEN_ID_REF) REFERENCES T_ROLLEN
 (ID));
PROMPT Creating Foreign Key on 'T_STDSATZKATALOG';
ALTER TABLE T_STDSATZKATALOG ADD (CONSTRAINT
 STDSATZKATALOG_ARBEIT_FK FOREIGN KEY
 (WORK_AREA_ID) REFERENCES T_ARBEITSBEREICH
 (ID));
PROMPT Creating Foreign Key on 'T_STDSATZKATALOG';
ALTER TABLE T_STDSATZKATALOG ADD (CONSTRAINT
 STDSATZKATALOG_ORDNER_FK FOREIGN KEY
 (ORDNER_REF_ID) REFERENCES T_ORDNER
 (ID));
PROMPT Creating Foreign Key on 'T_STUNDENSAETZE';
ALTER TABLE T_STUNDENSAETZE ADD (CONSTRAINT
 STUNDENSAETZE_STDSATZKAT_FK FOREIGN KEY
 (STD_SATZ_KAT_REF_ID) REFERENCES T_STDSATZKATALOG
 (ID));
PROMPT Creating Foreign Key on 'T_STUNDENSAETZE';
ALTER TABLE T_STUNDENSAETZE ADD (CONSTRAINT
 STUNDENSAETZE_KOSTENATT_FK FOREIGN KEY
 (KOSTEN_ATTRIBUT_REF_ID) REFERENCES T_KOSTENATTRIBUT
 (ID));
 PROMPT Creating Foreign Key on 'T_ELEMENTVERSIONANDERUNG';
ALTER TABLE T_ELEMENTVERSIONANDERUNG ADD (CONSTRAINT
 ELEMANDERUNG_ELEMENTVERS_FK FOREIGN KEY
 (ELEM_VER_REF_ID) REFERENCES T_ELEMENTVERSION
 (UUIDKEVERSION));
PROMPT Creating Foreign Key on 'T_BAUSTEINVERSIONANDERUNG';
ALTER TABLE T_BAUSTEINVERSIONANDERUNG ADD (CONSTRAINT
 BAUSANDERUNG_BAUSTEINVERS_FK FOREIGN KEY
 (KB_VERSION_ID) REFERENCES T_BAUSTEINVERSION
 (KB_VERSION_UU_ID));
 
PROMPT Creating Index 'BAUS_ORD_FK_I';
CREATE INDEX BAUS_ORD_FK_I ON T_BAUSTEIN
 (ORDNER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSKOST_BAUS_VERS_FK_I';
CREATE INDEX BAUSKOST_BAUS_VERS_FK_I ON T_BAUSTEINKOSTEN
 (KB_REF_UU_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSKOST_KOSTEN_ATTR_FK_I';
CREATE INDEX BAUSKOST_KOSTEN_ATTR_FK_I ON T_BAUSTEINKOSTEN
 (KOSTEN_ATTRIBUT_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSVERS_BAUST_KLASSE_FK_I';
CREATE INDEX BAUSVERS_BAUST_KLASSE_FK_I ON T_BAUSTEINVERSION
 (ENUM_BAUSTEIN_KLASSE_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSVERS_BAUSTEIN_TYP_FK_I';
CREATE INDEX BAUSVERS_BAUSTEIN_TYP_FK_I ON T_BAUSTEINVERSION
 (ENUM_BAUSTEIN_TYP_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSVERS_BENUTZER_FK_I';
CREATE INDEX BAUSVERS_BENUTZER_GEA_FK_I ON T_BAUSTEINVERSION
 (GEAENDERT_VON_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSVERS_BENUTZER_ERST_FK_I';
CREATE INDEX BAUSVERS_BENUTZER_ERST_FK_I ON T_BAUSTEINVERSION
 (ERSTELLER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSVERS_STATUS_FK_I';
CREATE INDEX BAUSVERS_STATUS_FK_I ON T_BAUSTEINVERSION
 (ENUM_STATUS_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSTEINVERSION_BAUSTEIN_FK_I';
CREATE INDEX BAUSTEINVER_BAUSTEIN_FK_I ON T_BAUSTEINVERSION
 (KB_REF_UU_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMENT_ORDNER_FK_I';
CREATE INDEX ELEMENT_ORDNER_FK_I ON T_ELEMENT
 (ORDNER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMVERS_ELEMKATEG_FK_I';
CREATE INDEX ELEMVERS_ELEMKATEG_FK_I ON T_ELEMENTVERSION
 (KATEGORIE_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMVERS_ELEMENT_FK_I';
CREATE INDEX ELEMVERS_ELEMENT_FK_I ON T_ELEMENTVERSION
 (KE_REF_UU_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMVERS_BENUTZER_GEA_FK_I';
CREATE INDEX ELEMVERS_BENUTZER_GEA_FK_I ON T_ELEMENTVERSION
 (GEAENDERT_VON_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMVERS_BENUTZER_ERST_FK_I';
CREATE INDEX ELEMVERS_BENUTZER_ERST_FK_I ON T_ELEMENTVERSION
 (ERSTELLER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMVERS_STATUS_FK_I';
CREATE INDEX ELEMVERS_STATUS_FK_I ON T_ELEMENTVERSION
 (ENUM_STATUS_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMENTWERTE_ELEMVERS_FK_I';
CREATE INDEX ELEMENTWERTE_ELEMVERS_FK_I ON T_ELEMENTWERTE
 (ELEM_VER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMENTWERTE_KOST_ATTR_FK_I';
CREATE INDEX ELEMENTWERTE_KOST_ATTR_FK_I ON T_ELEMENTWERTE
 (KOSTEN_ATTRIBUT_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'TRANSITION_ZUR_STATUS_FK_I';
CREATE INDEX TRANSITION_ZUR_STATUS_FK_I ON T_ENUM_TRANSITION
 (ZUR_STATUS)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'TRANSITION_VON_STATUS_FK_I';
CREATE INDEX TRANSITION_VON_STATUS_FK_I ON T_ENUM_TRANSITION
 (VON_STATUS)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'KOSTENATTR_PLANKOSTEN_KAT_FK_I';
CREATE INDEX KOSTENATTR_PLANKOST_KAT_FK_I ON T_KOSTENATTRIBUT
 (PLAN_KOSTEN_KATEGORIE_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ORDNER_OBJEKTTYP_FK_I';
CREATE INDEX ORDNER_OBJEKTTYP_FK_I ON T_ORDNER
 (OBJEKT_TYP_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ORDNER_ORDNER_FK_I';
CREATE INDEX ORDNER_ORDNER_FK_I ON T_ORDNER
 (ORDNER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'PLAN_KOST_INVESTANT_FK_I';
CREATE INDEX PLAN_KOST_INVESTANT_FK_I ON T_PLANKOSTENKATEGORIE
 (T_ENUM_INVESTANTEIL_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_BE_ELEMENT_FK_I';
CREATE INDEX REL_BE_ELEMENT_FK_I ON T_REL_BAUSTEIN_ELEMENT
 (KE_REF_UU_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_BE_BAUSTEINVERSION_FK_I';
CREATE INDEX REL_BE_BAUSTEINVERSION_FK_I ON T_REL_BAUSTEIN_ELEMENT
 (KBVERSIONREFUUID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_BAUS_DOK_BAUSTEINVERSION_FK_I';
CREATE INDEX REL_BAUS_DOK_BAUSTVER_FK_I ON T_REL_BAUSVERSION_DOKUMENTPOOL
 (KB_VERSION_UU_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_BEN_ARB_ARBEITSBEREICH_FK_I';
CREATE INDEX REL_BEN_ARB_ARBEITS_FK_I ON T_REL_BENUTZER_ARBEITSBEREICH
 (ARBEITSBEREICH_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_BEN_ARB_BENUTZER_FK_I';
CREATE INDEX REL_BEN_ARB_BENUTZER_FK_I ON T_REL_BENUTZER_ARBEITSBEREICH
 (USER_ID_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_BEN_ROLLEN_ROLLEN_FK_I';
CREATE INDEX REL_BEN_ROLLEN_ROLLEN_FK_I ON T_REL_BENUTZER_ROLLEN
 (ROLLE_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_BEN_ROLLEN_BENUTZER_FK_I';
CREATE INDEX REL_BEN_ROLLEN_BENUT_FK_I ON T_REL_BENUTZER_ROLLEN
 (USER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_ELEM_DOK_ELEMVERS_FK_I'; 
CREATE INDEX REL_ELEM_DOK_ELEMVERS_FK_I ON T_REL_ELEMVERSION_DOKUMENTPOOL
 (UUIDKEVERSION_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_ELEM_DOKUMENT_DOK_FK_I';
CREATE INDEX REL_ELEM_DOKUMENT_DOK_FK_I ON T_REL_ELEMVERSION_DOKUMENTPOOL
 (ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_ROLLEN_RECHT_ROLL_FK_I';
CREATE INDEX REL_ROLLEN_RECHT_ROLL_FK_I ON T_REL_ROLLEN_RECHT
 (ROLLEN_ID_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_ROLLEN_RECHT_RECHT_FK_I';
CREATE INDEX REL_ROLLEN_RECHT_RECHT_FK_I ON T_REL_ROLLEN_RECHT
 (RECHT_ID_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_ROLLEN_ROLLEN_ROLL_FK_I';
CREATE INDEX REL_ROLLEN_ROLLEN_ROLL_FK_I ON T_REL_ROLLEN_ROLLEN
 (ROLLEN_ID_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'REL_ROLLEN_ROLLEN_MANAG_FK_I';
CREATE INDEX REL_ROLLEN_ROLLEN_MANAG_FK_I ON T_REL_ROLLEN_ROLLEN
 (MANAGED_ROLLEN_ID_REF)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'STDSATZKATALOG_ARBEIT_FK_I';
CREATE INDEX STDSATZKATALOG_ARBEIT_FK_I ON T_STDSATZKATALOG
 (WORK_AREA_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'STDSATZKATALOG_ORDNER_FK_I';
CREATE INDEX STDSATZKATALOG_ORDNER_FK_I ON T_STDSATZKATALOG
 (ORDNER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'STUNDENSAETZE_STDSATZKAT_FK_I';
CREATE INDEX STUNDENSAETZE_STDSATZKAT_FK_I ON T_STUNDENSAETZE
 (STD_SATZ_KAT_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'STUNDENSAETZE_KOSTENATT_FK_I';
CREATE INDEX STUNDENSAETZE_KOSTENATT_FK_I ON T_STUNDENSAETZE
 (KOSTEN_ATTRIBUT_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMANDERUNG_ELEMENTVERS_FK_I';
CREATE INDEX ELEMANDERUNG_ELEMENTVERS_FK_I ON T_ELEMENTVERSIONANDERUNG
 (ELEM_VER_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
PROMPT Creating Index 'BAUSANDERUNG_ELEMENTVERS_FK_I';
CREATE INDEX BAUSANDERUNG_ELEMENTVERS_FK_I ON T_BAUSTEINVERSIONANDERUNG
 (KB_VERSION_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
 
 
PROMPT Creating Unique Key on 'T_BAUSTEIN';
ALTER TABLE T_BAUSTEIN
 ADD (CONSTRAINT BAUSTEIN_BAUSTEIN_NR_UK UNIQUE 
  (BAUSTEIN_NR)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_BAUSTEIN';
ALTER TABLE T_BAUSTEIN
 ADD (CONSTRAINT BAUSTEIN_BEZEICHNUNG_UK UNIQUE 
  (BEZEICHNUNG)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_BENUTZER';
ALTER TABLE T_BENUTZER
 ADD (CONSTRAINT BENUTZER_KUMS_USER_ID_UK UNIQUE 
  (KUMS_USER_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_ELEMENT';
ALTER TABLE T_ELEMENT
 ADD (CONSTRAINT ELEMENT_ELEMENT_NR_UK UNIQUE 
  (ELEMENT_NR)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_ELEMENT';
ALTER TABLE T_ELEMENT
 ADD (CONSTRAINT ELEMENT_BEZEICHNUNG_UK UNIQUE 
  (BEZEICHNUNG)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_ELEMENTKATEGORIE';
ALTER TABLE T_ELEMENTKATEGORIE
 ADD (CONSTRAINT ELEMENTKATEG_BEZEICHNUNG_UK UNIQUE 
  (BEZEICHNUNG)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_ORDNER';
ALTER TABLE T_ORDNER
 ADD (CONSTRAINT ORDNER_BEZEICHNUNG_UK UNIQUE 
  (BEZEICHNUNG, ORDNER_REF_ID)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_PLANKOSTENKATEGORIE';
ALTER TABLE T_PLANKOSTENKATEGORIE
 ADD (CONSTRAINT PLAN_KOSTEN_KATEGORIE_UK UNIQUE 
  (PLAN_KOSTEN_KATEGORIE)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@);
PROMPT Creating Unique Key on 'T_PLANKOSTENKATEGORIE';
ALTER TABLE T_PLANKOSTENKATEGORIE
 ADD (CONSTRAINT PLAN_KOSTEN_KAT_ORDER_UK UNIQUE 
  (ORDER_NR)
 USING INDEX 
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@); 

PROMPT Creating Index 'BAUSTEINVERSION_ORDER_GUELT_I';
CREATE INDEX BAUSTEINVER_ORDER_GUELT_I ON T_BAUSTEINVERSION
 (GUELTIG_BIS)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSTEINVERSION_SEL_GEAEND_I';
CREATE INDEX BAUSTEINVER_SEL_GEAEND_I ON T_BAUSTEINVERSION
 (GEAENDERT_AM)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;

PROMPT Creating Index 'ELEMENTVERSION_ORDER_GUELT_I';
CREATE INDEX ELEMENTVER_ORDER_GUELT_I ON T_ELEMENTVERSION
 (GUELTIG_BIS)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
PROMPT Creating Index 'ORDNER_ORDER_BEZEI_I';
CREATE INDEX ORDNER_ORDER_BEZEI_I ON T_ORDNER
 (BEZEICHNUNG)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'STDSATZKAT_ORDER_BEZEI_I';
CREATE INDEX STDSATZKAT_ORDER_BEZEI_I ON T_STDSATZKATALOG
 (BEZEICHNUNG)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'BAUSTEIN_SEL_INAK_VON_I';
CREATE INDEX BAUSTEIN_SEL_INAK_VON_I ON T_BAUSTEIN
 (INAKTIV_VON)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'INVESTANTEIL_SEL_KAT_I';
CREATE INDEX INVESTANTEIL_SEL_KAT_I ON T_ENUM_INVESTANTEIL
 (KATEGORIE)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'KOSTENATT_SEL_X_PREIS_PRO_I';
CREATE INDEX KOSTENATT_SEL_X_PREIS_PRO_I ON T_KOSTENATTRIBUT
 (X_PREIS_PRO_EINHEIT)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
PROMPT Creating Index 'ELEMENT_SEL_INAKTIV_I';
CREATE INDEX ELEMENT_SEL_INAKTIV_I ON T_ELEMENT
 (X_INAKTIV)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
PROMPT Creating Index 'BENUTZER_SEL_AKTIV_I';
CREATE INDEX BENUTZER_SEL_AKTIV_I ON T_BENUTZER
 (AKTIV)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
PROMPT Creating Index 'BENUTZER_SEL_NACHNAME_I';
CREATE INDEX BENUTZER_SEL_NACHNAME_I ON T_BENUTZER
 (NACHNAME)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
PROMPT Creating Index 'BENUTZER_SEL_VORNAME_I';
CREATE INDEX BENUTZER_SEL_VORNAME_I ON T_BENUTZER
 (VORNAME)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
PROMPT Creating Index 'ARBEITSBEREICH_SEL_BEZEI_I';
CREATE INDEX ARBEITSBEREICH_SEL_BEZEI_I ON T_ARBEITSBEREICH
 (BEZEICHNUNG)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;




CREATE INDEX S_KATALOG_BEZ_ORDNER_INDEX ON T_STDSATZKATALOG(BEZEICHNUNG,ORDNER_REF_ID);
CREATE INDEX S_KATALOG_ORDNER_WA_INDEX ON T_STDSATZKATALOG(ORDNER_REF_ID,WORK_AREA_ID);


insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (1, 'Konstruktion', 'Mechanik', 1);
insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (2, 'Anfertigung', 'Mechanik', 2);
insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (3, 'Material und Kaufteile', 'Mechanik', 4);
insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (4, 'Montage, Inbetriebnahme', 'Mechanik', 3);
insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (5, 'Plg, Konstr, Doku.', 'Elektrik', 5);
insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (6, 'Montage, Installation', 'Elektrik', 7);
insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (7, 'Inbetriebnahme', 'Elektrik', 8);
insert into T_ENUM_INVESTANTEIL (ID, INVESTITIONS_ANTEIL, KATEGORIE, ORDER_NR) values (8, 'Anfertigung (Kaufteile)', 'Elektrik', 6);
select seq_investment_part.NEXTVAL from dual;
select seq_investment_part.NEXTVAL from dual;
select seq_investment_part.NEXTVAL from dual;
select seq_investment_part.NEXTVAL from dual;
select seq_investment_part.NEXTVAL from dual;
select seq_investment_part.NEXTVAL from dual;
select seq_investment_part.NEXTVAL from dual;
select seq_investment_part.NEXTVAL from dual;

insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (1, '‹bergreifende Mechanik', 1, 1,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (2, 'Konstruktion und ROBCAD', 2, 1,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (3, 'Roboter Offline-Programmierung', 3, 1,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (4, 'Anfertigung', 4, 2,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (5, 'Kaufteile', 5, 3,1);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (6, 'Montage, Inbetriebnahme bei AN', 6, 4,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (7, 'Montage, Inbetriebnahme bei AG', 7, 4,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (8, '‹bergreifende Elektrik', 8, 5,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (9, 'Konstruktion HW', 9, 5,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (10, 'Konstruktion SW', 10, 5,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (11, 'Installation Montage', 11, 6,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (12, 'Inbetriebnahme', 12, 7,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (13, 'Roboter Online-Programmierung', 13, 7,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (14, 'Installationsmaterial', 14, 6,0);
insert into T_PLANKOSTENKATEGORIE (ID, PLAN_KOSTEN_KATEGORIE, ORDER_NR, T_ENUM_INVESTANTEIL_REF,BEISTELLUNG_AG) values (15, 'Kaufteile Elektro', 15, 8,1);
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;
select seq_cost_plan_category.NEXTVAL from dual;

insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - ‹bergeordnete Kosten',unistr('\20ac'), 1,100,0,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Projektleiter','Std.', 1,101,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Baustellenleiter','Std.', 1,102,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Planer','Std.', 1,103,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Virtuelle Realit‰t (Process Designer)','Std.', 2,110,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Off-Line-Untersuchung (RobCAD)','Std.', 2,111,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - CAD-Konstruktion','Std.', 2,112,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Ablaufsimulation','Std.', 2,113,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Off-Line-Programmierung (RobCAD)','Std.', 3, 120,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - CAD-/CAM-Programmierung (2D/3D)','Std.', 4,130,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Bankarbeit','Std.', 4,131,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Kleine Maschine','Std.', 4,132,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Mittlere Maschine','Std.', 4,133,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Groﬂe Maschine','Std.', 4,134,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Messmaschine','Std.', 4,135,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Fremdanfertigung (als Kaufteil)',unistr('\20ac'), 4,136,0,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Baustahl','Kg', 4,137,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Werkzeugstahl, NE-Metalle','Kg', 4,138,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Kaufteile',unistr('\20ac'), 5,162,0,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Verpackung, Fracht',unistr('\20ac'), 4,139,0,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Potentielle Beistellung',unistr('\20ac'), 5,163,0,1);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Montage, Inbetriebnahme AN','Std.', 6,140,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Montage, Inbetriebnahme AG','Std.', 7,150,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Samstag-Zuschlag','Std.', 7,151,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'M - Sonn- und Feiertagszuschlag/Nachtschicht','Std.', 7,152,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - ‹bergeordnete Kosten',unistr('\20ac'), 8,200,0,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Projektleiter','Std.', 8,201,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Baustellenleiter','Std.', 8,202,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Planer','Std.', 8,203,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Konstruktion Hardware (incl. Doku)','Std.', 9,210,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Konstruktion Software','Std.', 10,220,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Montage, Installation','Std.', 11,240,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Inbetriebnahme','Std.', 12,260,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Samstag-Zuschlag','Std.', 12,261,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Sonn- und Feiertagszuschlag/Nachtschicht','Std.', 12,262,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Roboter-Online Programmierung','Std.', 13,270,1,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Installationsmaterial',unistr('\20ac'), 14,250,0,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Kaufteil',unistr('\20ac'), 15,230,0,0);
insert into T_KOSTENATTRIBUT (ID, BEZEICHNUNG,EINHEIT,PLAN_KOSTEN_KATEGORIE_REF, ORDER_NR,X_PREIS_PRO_EINHEIT,BEISTELLUNG_AG) values (seq_cost_attribute.NEXTVAL, 'E - Potentielle Beistellung',unistr('\20ac'), 15,231,0,1);

insert into T_ENUM_STATUS (ID, BEZEICHNUNG, READ_ONLY, ADD_ALLOWED, SAVE_ALLOWED, DELETE_ALLOWED, BACK_ALLOWED, PRINT_ALLOWED, EXPORT_ALLOWED) values (0, 'NEW', 0, 0, 1, 0, 1, 1, 0);
insert into T_ENUM_STATUS (ID, BEZEICHNUNG, READ_ONLY, ADD_ALLOWED, SAVE_ALLOWED, DELETE_ALLOWED, BACK_ALLOWED, PRINT_ALLOWED, EXPORT_ALLOWED) values (1, 'CREATED', 0, 1, 1, 1, 1, 1, 1);
insert into T_ENUM_STATUS (ID, BEZEICHNUNG, READ_ONLY, ADD_ALLOWED, SAVE_ALLOWED, DELETE_ALLOWED, BACK_ALLOWED, PRINT_ALLOWED, EXPORT_ALLOWED) values (2, 'TO_BE_APPROVED', 1, 1, 0, 1, 1, 1, 1);
insert into T_ENUM_STATUS (ID, BEZEICHNUNG, READ_ONLY, ADD_ALLOWED, SAVE_ALLOWED, DELETE_ALLOWED, BACK_ALLOWED, PRINT_ALLOWED, EXPORT_ALLOWED) values (3, 'APPROVED', 1, 1, 0, 1, 1, 1, 1);
insert into T_ENUM_STATUS (ID, BEZEICHNUNG, READ_ONLY, ADD_ALLOWED, SAVE_ALLOWED, DELETE_ALLOWED, BACK_ALLOWED, PRINT_ALLOWED, EXPORT_ALLOWED) values (4, 'IN_PROGRESS', 0, 1, 1, 1, 1, 1, 1);
insert into T_ENUM_STATUS (ID, BEZEICHNUNG, READ_ONLY, ADD_ALLOWED, SAVE_ALLOWED, DELETE_ALLOWED, BACK_ALLOWED, PRINT_ALLOWED, EXPORT_ALLOWED) values (5, 'IN_USE', 1, 1, 0, 0, 1, 1, 1);

insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (0,1, 'SAVE_NEW',1);
insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (1,2, 'RELEASE_FOR_APPROVEMENT',0);
insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (2,3, 'APPROVE',0);
insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (3,5, 'RELEASE',1);
insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (2,4, 'MODIFY',0);
insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (4,2, 'RELEASE_FOR_APPROVEMENT',0);
insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (3,4, 'MODIFY',0);
insert into T_ENUM_TRANSITION (VON_STATUS, ZUR_STATUS, BEZEICHNUNG, BATCH) values (5,4, 'MODIFY',0);

insert into T_ENUM_OBJEKTTYP (ID, OBJEKT_TYP) values (1, 'ELEMENT' );
insert into T_ENUM_OBJEKTTYP (ID, OBJEKT_TYP) values (2, 'COMPONENT');
insert into T_ENUM_OBJEKTTYP (ID, OBJEKT_TYP) values (3, 'HOURLY_RATE_CATALOG');
insert into T_ENUM_OBJEKTTYP (ID, OBJEKT_TYP) values (4, 'USER');
insert into T_ENUM_OBJEKTTYP (ID, OBJEKT_TYP) values (5, 'WORK_AREA');
insert into T_ENUM_OBJEKTTYP (ID, OBJEKT_TYP) values (6, 'FOLDER');

insert into T_ROLLEN(ID,BEZEICHNUNG,BESCHREIBUNG) values(1,'ROOT_ADMINISTRATOR','root administrator');
insert into T_ROLLEN(ID,BEZEICHNUNG,BESCHREIBUNG) values(2,'ADMINISTRATOR','administrator');
insert into T_ROLLEN(ID,BEZEICHNUNG,BESCHREIBUNG) values(3,'KALKULATOR','Kalkulator');

insert into T_REL_ROLLEN_ROLLEN (ROLLEN_ID_REF, MANAGED_ROLLEN_ID_REF) values (1,2);
insert into T_REL_ROLLEN_ROLLEN (ROLLEN_ID_REF, MANAGED_ROLLEN_ID_REF) values (1,3);
insert into T_REL_ROLLEN_ROLLEN (ROLLEN_ID_REF, MANAGED_ROLLEN_ID_REF) values (2,3);

insert into T_STDSATZKATALOG(ID,BEZEICHNUNG,BESCHREIBUNG,ERSTELLER_REF_ID,ERSTELLT_AM,GEAENDERT_VON_REF_ID,GEAENDERT_AM) values(seq_hourly_rate_catalog.NEXTVAL,' 1 '||unistr('\20ac'),null,1,SYSDATE,null,null);

insert into T_STUNDENSAETZE (ID,WERT,KOSTEN_ATTRIBUT_REF_ID,STD_SATZ_KAT_REF_ID) select seq_hourly_rate.NEXTVAL,1, ID,1 from T_KOSTENATTRIBUT where X_PREIS_PRO_EINHEIT=1;

insert into T_ORDNER (ID, BEZEICHNUNG, ORDNER_REF_ID, OBJEKT_TYP_REF_ID) values (1,'Administration',null,6);
insert into T_ORDNER (ID, BEZEICHNUNG, ORDNER_REF_ID, OBJEKT_TYP_REF_ID) values (2,'WorkAreaAdministration',1,5);
insert into T_ORDNER (ID, BEZEICHNUNG, ORDNER_REF_ID, OBJEKT_TYP_REF_ID) values (3,'UserAdministration',2,4);
insert into T_ORDNER (ID, BEZEICHNUNG, ORDNER_REF_ID, OBJEKT_TYP_REF_ID) values (4,'CalculationSettingAdministration',null,6);
insert into T_ORDNER (ID, BEZEICHNUNG, ORDNER_REF_ID, OBJEKT_TYP_REF_ID) values (5,'HourlyRateCatalogAdministration',4,3);
insert into T_ORDNER (ID, BEZEICHNUNG, ORDNER_REF_ID, OBJEKT_TYP_REF_ID) values (6,'ElementAdministration',null,1);
insert into T_ORDNER (ID, UUIDORDNER, BEZEICHNUNG, ORDNER_REF_ID, OBJEKT_TYP_REF_ID) values (7,'PP-EMPLNEW-3-3-2004-14-47-51-259629-287867','ComponentAdministration',null,2);
select seq_folder.nextval from dual;
select seq_folder.nextval from dual;
select seq_folder.nextval from dual;
select seq_folder.nextval from dual;
select seq_folder.nextval from dual;
select seq_folder.nextval from dual;
select seq_folder.nextval from dual;

insert into T_ELEMENTKATEGORIE (ID, BEZEICHNUNG) values (seq_element_category.nextval,'Kategorie 1');
insert into T_ELEMENTKATEGORIE (ID, BEZEICHNUNG) values (seq_element_category.nextval,'Kategorie 2');
insert into T_ELEMENTKATEGORIE (ID, BEZEICHNUNG) values (seq_element_category.nextval,'Kategorie 3');
insert into T_ELEMENTKATEGORIE (ID, BEZEICHNUNG) values (seq_element_category.nextval,'Kategorie 4');
insert into T_ELEMENTKATEGORIE (ID, BEZEICHNUNG) values (seq_element_category.nextval,'Kategorie 5');
insert into T_ELEMENTKATEGORIE (ID, BEZEICHNUNG) values (seq_element_category.nextval,'Kategorie 6');

insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (1, 'Kapl', 'Cornelia','TCOKAPL','Frau',0,1,1,null);
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (2, 'Eberl', 'Heinrich-Johann','TEWEBE','Herr',0,1,1,'1;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (3, 'Roeckel', 'Juergen','TKRROE','Herr',0,1,1,'1;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (4, 'Wendl', 'Sebastian','VGFVE4D','Herr',0,1,1,'1;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (5, 'Bauer', 'Josef','TSABAU','Herr',0,1,1,'1;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (6, 'Byszio', 'Erwin','THBYSZE','Herr',0,1,1,'1;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (7, 'Polak', 'Manfred','TECPOL','Herr',0,1,1,'1;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (8, 'Dittmann', 'Uwe','TWODTT','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (9, 'Glaser', 'Frank','EB0GLAS','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (10, 'Koether', 'Reiner','EKOETHR','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (11, 'Lindemann', 'Udo','TP10LIN','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (12, 'Pasch', 'Erik','DPW0PEK','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (13, 'Ronowski', 'Peter','ERONOW4','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (14, 'Griguhn', 'Michael','1','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (15, 'Bischoff', 'Lars','2','Herr',0,1,1,'2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (16, 'Jensen', 'Gunnar','EGJENSE','Herr',0,1,1,'1;2;');
insert into T_BENUTZER (USER_ID, NACHNAME,VORNAME, KUMS_USER_ID,ANREDE,STATUS_ELEMENT_FREIGEGEBEN,DEFAULT_STD_SATZ_KAT_REF_ID, AKTIV,BENUTZER_ADMIN_ARBEITS) values (17, 'Ginzkey', 'Henrik','D4F9DVG','Herr',0,1,1,'1;2;');
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
select seq_user.nextval from dual;
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (1,1);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (2,2);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (3,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (4,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (5,2);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (6,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (7,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (8,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (9,2);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (10,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (11,2);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (12,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (13,2);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (14,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (15,3);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (16,2);
insert into T_REL_BENUTZER_ROLLEN (USER_REF_ID, ROLLE_REF_ID) values (17,2);

insert into T_ARBEITSBEREICH (ID,BEZEICHNUNG) values (1,'Audi');
insert into T_ARBEITSBEREICH (ID,BEZEICHNUNG) values (2,'VW');
select SEQ_WORK_AREA.nextval from dual;
select SEQ_WORK_AREA.nextval from dual;


insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (2,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (3,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (4,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (5,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (6,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (7,1);

insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (8,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (9,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (10,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (11,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (12,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (13,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (14,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (15,2);

insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (16,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (16,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (17,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (17,2);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (1,1);
insert into T_REL_BENUTZER_ARBEITSBEREICH(USER_ID_REF,ARBEITSBEREICH_REF) values (1,2);

insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Arbeitsplatzausstattung');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Clinchtechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Container');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Falztechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'FoerderUndSpeichertechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Gebaeudetechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Klebetechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Lasertechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'MessUndPrueftechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Niettechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Roboter');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Roboterzubehoer');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Schraubtechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Schutztechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'SchweissUndLoettechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Sonderbetriebsmittel');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Stahlbau');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Standardbetriebsmittel');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Steuerungstechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Trenntechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'VerbindungsUndTrenntechnik');
insert into T_ENUM_BAUSTEINTYP (ID, BAUSTEIN_TYP) values (seq_component_type.nextval,'Vorrichtungstechnik');

insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'BuildingServices');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Clamp');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Consumable');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Container');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Conveyer');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Device');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Dock_System');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Electric');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Fixture');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Flange');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Gripper');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Gun');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Human');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'LightSensor');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'PersonalEquipment');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'PlcResource');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'PmEquipmentPrototype');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'PmResourceLibrary');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'PmToolPrototype');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'ProximitySensor');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Quality');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Robot');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'RobotEquipment');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Security_Window');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Shelf');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'SteelConstruction');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Turn_Table');
insert into T_ENUM_BAUSTEINKLASSE (ID, BAUSTEIN_KLASSE) values (seq_component_class.nextval,'Work_Table');

insert into T_RECHT (RECHT_ID, KODE) values (1,'MANAGE_WORK_AREA');
insert into T_RECHT (RECHT_ID, KODE) values (2,'MANAGE_USER');
insert into T_RECHT (RECHT_ID, KODE) values (3,'MANAGE_HOURLY_RATE');
insert into T_RECHT (RECHT_ID, KODE) values (4,'MANAGE_COMPONENT');
insert into T_RECHT (RECHT_ID, KODE) values (5,'MANAGE_ELEMENT');
insert into T_RECHT (RECHT_ID, KODE) values (6,'VIEW_USER');
insert into T_RECHT (RECHT_ID, KODE) values (7,'UPDATE_FOLDER');

insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(1,1);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(1,2);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(1,7);

insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(2,2);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(2,3);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(2,4);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(2,5);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(2,7);

insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(3,3);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(3,4);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(3,5);
insert into T_REL_ROLLEN_RECHT (ROLLEN_ID_REF, RECHT_ID_REF) values(3,6);
