  -- TABLE T_NEWS
 CREATE TABLE T_NEWS 
( ID NUMBER(12) not null
, UEBERSCHRIFT varchar2(50)
, BESCHREIBUNG varchar2(4000)
, GUELTIG_AB DATE
, GUELTIG_BIS DATE
, AKTIV NUMBER(1,0)
)
PCTFREE 10 
TABLESPACE ${prop.application.db.tablespace.table};

 ALTER TABLE T_NEWS ADD (CONSTRAINT T_NEWS_PK PRIMARY KEY (ID) USING INDEX 
 PCTFREE 10
 TABLESPACE ${prop.application.db.tablespace.index});
 
PROMPT Creating Sequence 'SEQ_NEWS';
CREATE SEQUENCE SEQ_NEWS
 INCREMENT BY 1
 START WITH 1 
 NOMAXVALUE 
 NOMINVALUE
 NOCYCLE;
