ALTER TABLE T_MARKE ADD NUTZUNG_INAKTIV_IMG VARCHAR2(50);
UPDATE T_MARKE SET NUTZUNG_INAKTIV_IMG ='nutzer_inactiv_AU.jpg' WHERE ID='AU';
UPDATE T_MARKE SET NUTZUNG_INAKTIV_IMG ='nutzer_inactiv_VW.jpg' WHERE ID='VW';

COMMIT ;