ALTER TABLE T_BENUTZER ADD DEAKTIVIERUNGS_DATUM DATE;
ALTER TABLE T_BENUTZER ADD ANONYMISIERT NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE T_BENUTZER MODIFY KUMS_USER_ID VARCHAR2(36 CHAR);


-- PROD: Zum Release-Datum bei allen inaktiven User das Deaktivierungsdatum=today setzen 
--  Maintenance Nr: 10212801
UPDATE T_BENUTZER SET DEAKTIVIERUNGS_DATUM=SYSDATE WHERE AKTIV=0;