UPDATE T_PLANKOSTENKATEGORIE SET PLAN_KOSTEN_KATEGORIE = ' Konstruktion und Simulation' WHERE ID = 2;
UPDATE T_BAUSTEINVERSIONANDERUNG  SET ANDERUNG = REPLACE(ANDERUNG, '(RobCAD)', '(Simulation)') where ANDERUNG like '%(RobCAD)';
UPDATE T_ELEMENTVERSIONANDERUNG  SET ANDERUNG = REPLACE(ANDERUNG, '(RobCAD)', '(Simulation)') where ANDERUNG like '%(RobCAD)';