ALTER TABLE T_BAUSTEINVERSIONANDERUNG ADD ANDERUNG_ART VARCHAR2(300 char);
ALTER TABLE T_BAUSTEINVERSIONANDERUNG ADD ALTER_KOMMENTAR VARCHAR2(4000 char);
ALTER TABLE T_BAUSTEINVERSIONANDERUNG ADD NEUER_KOMMENTAR VARCHAR2(4000 char);

ALTER TABLE T_ELEMENTVERSIONANDERUNG ADD ANDERUNG_ART VARCHAR2(300 char);
ALTER TABLE T_ELEMENTVERSIONANDERUNG ADD ALTER_KOMMENTAR VARCHAR2(4000 char);
ALTER TABLE T_ELEMENTVERSIONANDERUNG ADD NEUER_KOMMENTAR VARCHAR2(4000 char);

ALTER TABLE T_REL_BAUSTEIN_ELEMENT ADD KE_VERSION_REF_UUID number(19,0);
ALTER TABLE T_REL_BAUSTEIN_ELEMENT ADD KB_STAND_REF_UUID number(19,0);

PROMPT Creating Foreign Key on 'T_REL_BAUSTEIN_ELEMENT';
ALTER TABLE T_REL_BAUSTEIN_ELEMENT ADD (CONSTRAINT
 REL_BE_ELEMENTVERSION_FK FOREIGN KEY 
 (KE_VERSION_REF_UUID) REFERENCES T_ELEMENTVERSION (UUIDKEVERSION));
PROMPT Creating Foreign Key on 'T_REL_BAUSTEIN_ELEMENT';
ALTER TABLE T_REL_BAUSTEIN_ELEMENT ADD (CONSTRAINT
 REL_BE_BAUSTEINSTAND_FK FOREIGN KEY 
 (KB_STAND_REF_UUID) REFERENCES T_BAUSTEINSTAND(ID));
 
 
UPDATE T_REL_BAUSTEIN_ELEMENT RBE SET KE_VERSION_REF_UUID=(select max(UUIDKEVERSION) from T_ELEMENTVERSION where KE_REF_UU_ID=RBE.KE_REF_UU_ID and ENUM_STATUS_REF_ID in (5,4));
UPDATE T_REL_BAUSTEIN_ELEMENT SET KB_STAND_REF_UUID=(select ID from T_BAUSTEINSTAND where KB_VERSION_REF_ID=KBVERSIONREFUUID); 

PROMPT Removing old columns From 'T_REL_BAUSTEIN_ELEMENT';
ALTER TABLE T_REL_BAUSTEIN_ELEMENT DROP COLUMN KE_REF_UU_ID CASCADE CONSTRAINTS;
ALTER TABLE T_REL_BAUSTEIN_ELEMENT DROP COLUMN KBVERSIONREFUUID CASCADE CONSTRAINTS;


ALTER TABLE T_BAUSTEINVERSIONANDERUNG ADD KB_STAND_REF_ID number(19,0);
ALTER TABLE T_BAUSTEINVERSIONANDERUNG ADD (CONSTRAINT
 KB_STAND_AND_FK FOREIGN KEY 
 (KB_STAND_REF_ID) REFERENCES T_BAUSTEINSTAND(ID));
UPDATE T_BAUSTEINVERSIONANDERUNG SET KB_STAND_REF_ID=(select max(ID) from T_BAUSTEINSTAND where KB_VERSION_REF_ID=KB_VERSION_ID);
ALTER TABLE T_BAUSTEINVERSIONANDERUNG DROP COLUMN KB_VERSION_ID CASCADE CONSTRAINTS;

ALTER TABLE T_ELEMENTVERSIONANDERUNG ADD EINHEIT VARCHAR2(10 char);
UPDATE T_ELEMENTVERSIONANDERUNG an SET an.EINHEIT = (select EINHEIT from T_KOSTENATTRIBUT where BEZEICHNUNG = an.ANDERUNG);

ALTER TABLE T_BAUSTEINVERSIONANDERUNG ADD EINHEIT VARCHAR2(10 char);
UPDATE T_BAUSTEINVERSIONANDERUNG an SET an.EINHEIT = (select EINHEIT from T_KOSTENATTRIBUT where BEZEICHNUNG = an.ANDERUNG);

commit;