CREATE INDEX KB_VERSION_I ON T_BAUSTEINSTAND
 (KB_VERSION_REF_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@;
 
CREATE INDEX KB_STAND_I ON T_REL_BAUSTEIN_ELEMENT
 (KB_STAND_REF_UUID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
 
CREATE INDEX KE_VERSION_I ON T_REL_BAUSTEIN_ELEMENT
 (KE_VERSION_REF_UUID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 
  
CREATE INDEX KBN_STAND_I ON T_REL_BAUSVERSION_NUTZER
 (KB_STAND_ID)
 PCTFREE 10
 TABLESPACE @prop.application.db.tablespace.index@; 