ALTER TABLE T_DOKUMENTPOOL ADD ERSTELLT_AM DATE; 
ALTER TABLE T_DOKUMENTPOOL ADD ERSTELLER_REF_ID NUMBER (19,0);

ALTER TABLE T_ARBEITSBEREICH ADD ERSTELLT_AM DATE; 
ALTER TABLE T_ARBEITSBEREICH ADD ERSTELLER_REF_ID NUMBER (19,0);
ALTER TABLE T_ARBEITSBEREICH ADD GEAENDERT_AM DATE; 
ALTER TABLE T_ARBEITSBEREICH ADD GEAENDERT_VON_REF_ID NUMBER (19,0);

ALTER TABLE T_BENUTZER ADD ERSTELLT_AM DATE; 
ALTER TABLE T_BENUTZER ADD ERSTELLER_REF_ID NUMBER (19,0);
ALTER TABLE T_BENUTZER ADD GEAENDERT_AM DATE; 
ALTER TABLE T_BENUTZER ADD GEAENDERT_VON_REF_ID NUMBER (19,0);


ALTER TABLE T_ORDNER ADD ERSTELLT_AM DATE;
ALTER TABLE T_ORDNER MODIFY ERSTELLER_REF_ID NUMBER (19,0);
ALTER TABLE T_ORDNER ADD GEAENDERT_AM DATE; 
ALTER TABLE T_ORDNER ADD GEAENDERT_VON_REF_ID NUMBER (19,0);
