INSERT INTO T_ROLLEN VALUES (4,'BETRACHTER','Betrachter');
INSERT INTO T_REL_ROLLEN_ROLLEN VALUES(1,4);
INSERT INTO T_REL_ROLLEN_ROLLEN VALUES(2,4);

INSERT INTO T_REL_ROLLEN_RECHT VALUES(4,3);
INSERT INTO T_REL_ROLLEN_RECHT VALUES(4,4);
INSERT INTO T_REL_ROLLEN_RECHT VALUES(4,5);

ALTER TABLE T_BENUTZER ADD BENACHRICHTIGUNGS_OFF NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE T_BENUTZER add LETZTER_LOGOUT DATE ;