-------------------------------
-- PTS Ticket: 10152
-------------------------------

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma', 
(select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_01')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_011')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR  = '23_012')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_029')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_029')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_031')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_032')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_036')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_038')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_08')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_034')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_035')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
(select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_082')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '23_083')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_01')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_02')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_07')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_09')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_10')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_12')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_03')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_11')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_05')) ;

INSERT INTO T_BAUSTEINVERSIONANDERUNG (ANDERUNG_ID,ANDERUNG, NEUER_WERT, DATUM, LANG, ART, BENUTZER, KB_VERSION_ID)
VALUES (SEQ_BAUSTEIN_VERSION_ANDERUNG.nextval,'M - Off-Line-Programmierung (RobCAD)', '20,00', to_date('10.02.2005','dd.MM.yyyy'), 0, 'ATTRIBUTE_VALUE', 'polakma',
( select min(t.KB_VERSION_UU_ID) FROM T_BAUSTEINVERSION t , T_BAUSTEIN x  WHERE t.KB_REF_UU_ID = x.ID and  x.BAUSTEIN_NR = '26_08')) ;
