UPDATE T_BAUSTEINVERSIONANDERUNG SET NEUER_WERT=ANDERUNG,ANDERUNG='Verknüpfung' where ART='ADD_ELEMENT' and NEUER_WERT='hinzugefügt';
UPDATE T_BAUSTEINVERSIONANDERUNG SET ALTER_WERT=ANDERUNG,NEUER_WERT=null,ANDERUNG='Entfernung' where ART='REMOVE_ELEMENT';

commit;