UPDATE T_BIBLIOTHEK set COLOR='komponenten_kal_audi.gif' WHERE ID=1;
UPDATE T_BIBLIOTHEK set COLOR='komponenten_kal_vw.gif' WHERE ID=2;
UPDATE T_BIBLIOTHEK set COLOR='ergaenzungsbib_vw.gif' WHERE ID=3;

PROMPT CREATING BAUSTEINSTAND ;
INSERT INTO T_BAUSTEINSTAND(ID,STAND_DATE,KB_VERSION_REF_ID)
SELECT SEQ_BAUSTEINSTAND.NEXTVAL,COALESCE(GEAENDERT_AM,ERSTELLT_AM),KB_VERSION_UU_ID FROM T_BAUSTEINVERSION;

UPDATE T_BAUSTEINSTAND Z SET STAND_NUMMER=(select case when count(X.KB_VERSION_UU_ID)=0 then null else count(X.KB_VERSION_UU_ID) end from T_BAUSTEINVERSION X,T_BAUSTEINVERSION Y where X.KB_REF_UU_ID=Y.KB_REF_UU_ID and X.KB_VERSION_UU_ID<=Y.KB_VERSION_UU_ID  and X.ENUM_STATUS_REF_ID=5 and Y.KB_VERSION_UU_ID=Z.KB_VERSION_REF_ID);
COMMIT;

