package vwg.vw.km.integration.persistence.model;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

// Generated Jul 15, 2021 12:03:58 PM by Hibernate Tools 3.2.0.b9

/**
 * EnumTransitionCompPK generated by hbm2java
 */
public class EnumTransitionCompPK implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	
	/**
	 * @hibernate.many-to-one not-null="true"
	 * @hibernate.column name="FROM_STATUS"
	 * 
	 */
	@ManyToOne
	@JoinColumn(name = "VON_STATUS", nullable = false)
	private EnumStatusModel fromStatus;
	/**
	 * @hibernate.many-to-one not-null="true"
	 * @hibernate.column name="TO_STATUS"
	 * 
	 */
	@ManyToOne
	@JoinColumn(name = "ZUR_STATUS", nullable = false)
	private EnumStatusModel toStatus;

	public EnumTransitionCompPK() {
	}

	public EnumTransitionCompPK(EnumStatusModel fromStatus, EnumStatusModel toStatus) {
		this.fromStatus = fromStatus;
		this.toStatus = toStatus;
	}

	/**
	 * * @hibernate.many-to-one not-null="true"
	 * 
	 * @hibernate.column name="FROM_STATUS"
	 * 
	 */
	public EnumStatusModel getFromStatus() {
		return this.fromStatus;
	}

	public void setFromStatus(EnumStatusModel fromStatus) {
		this.fromStatus = fromStatus;
	}

	/**
	 * * @hibernate.many-to-one not-null="true"
	 * 
	 * @hibernate.column name="TO_STATUS"
	 * 
	 */
	public EnumStatusModel getToStatus() {
		return this.toStatus;
	}

	public void setToStatus(EnumStatusModel toStatus) {
		this.toStatus = toStatus;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("fromStatus").append("='").append(getFromStatus()).append("' ");
		buffer.append("toStatus").append("='").append(getToStatus()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

}
